masslight/ottehr

- packages/ehr/front-end/src/App.tsx
I've always liked using a switch statement for this type of function - I think it makes it easier to read & maintain.
If we like this change - we can also make a similar change in Navbar.tsx.
> cleanup getUserRole() method - switch statement for maintainability

- .github/workflows/build-and-deploy-PRODUCTION.yml
- .github/workflows/build-and-deploy-telemed-ehr.yml
- .github/workflows/build-and-deploy-telemed-intake.yml
- .github/workflows/build-and-deploy.yml
- .github/workflows/build.yml
- .npmrc
- README.md
- package.json
- packages/ehr-utils/package.json
- packages/ottehr-components/package.json
- packages/telemed-ehr/app/package.json
- packages/telemed-ehr/zambdas/package.json
- packages/telemed-intake/app/package.json
- packages/telemed-intake/package.json
- packages/telemed-intake/zambdas/package.json
- packages/telemed-intake/zambdas/src/package.json
- packages/telemed-intake/zambdas/src/playwright.config.ts
- packages/urgent-care-intake/app/package.json
- packages/urgent-care-intake/zambdas/package.json
- packages/utils/package.json
- pnpm-lock.yaml
- semver versions on packages
- removed 'engines' definitions from packages except the top package.json
- upgraded pnpm to 9.6.0 across github actions, in the engines spec, and in the README installation guide.
- removed unnecessary and incorrect node types devDeps, now all the packages will get node types for node 18 from top level package.json
> Fixing CI builds

- packages/telemed-intake/app/src/features/video-call/video-call.queries.ts
- packages/telemed-intake/app/src/pages/ReviewPaperwork.tsx
- packages/telemed-intake/app/src/pages/VideoChatPage.tsx
- packages/telemed-intake/app/vite.config.ts
https://github.com/masslight/ottehr/issues/537
> Videochat page updates

- packages/telemed-ehr/app/src/components/AppointmentStatusChipsCount.tsx
- packages/telemed-ehr/app/src/components/AppointmentStatusSwitcher.tsx
- packages/telemed-ehr/app/src/components/AppointmentTableRow.tsx
- packages/telemed-ehr/app/src/telemed/features/appointment/AppointmentFooter.tsx
- packages/telemed-ehr/app/src/telemed/features/appointment/AppointmentFooterButton.tsx
- packages/telemed-ehr/app/src/telemed/features/appointment/AppointmentSidePanel.tsx
- packages/telemed-ehr/app/src/telemed/features/appointment/ReviewTab/ReviewAndSignButton.tsx
- packages/telemed-ehr/app/src/telemed/hooks/useGetAppointmentAccessibility.ts
- packages/telemed-ehr/app/src/telemed/hooks/useIsReadOnly.ts
- packages/telemed-ehr/app/src/telemed/utils/appointment-accessibility.helper.ts
- packages/telemed-ehr/app/src/telemed/utils/getTelemedAppointmentStatusChip.tsx
- packages/telemed-ehr/app/src/telemed/utils/index.ts
- packages/telemed-intake/zambdas/src/appointment/cancel-in-person-appointment/index.ts
> cancel button fixes

- packages/telemed-ehr/app/src/components/inputs/ProvidersSelect.tsx
- packages/telemed-ehr/app/src/helpers/create-sample-appointments.ts
- packages/telemed-ehr/app/src/hooks/useOttehrUser.tsx
- packages/telemed-ehr/app/src/pages/Appointments.tsx
- packages/telemed-ehr/app/src/telemed/features/tracking-board/CreateDemoVisits.tsx
- packages/telemed-ehr/app/src/telemed/features/tracking-board/StateSelect.tsx
- packages/telemed-ehr/app/src/telemed/features/tracking-board/TrackingBoardFilters.tsx
- packages/telemed-ehr/app/src/telemed/features/tracking-board/TrackingBoardTable.tsx
- packages/telemed-ehr/app/src/telemed/features/tracking-board/TrackingBoardTabs.tsx
- packages/telemed-ehr/app/src/telemed/pages/TrackingBoardPage.tsx
- packages/telemed-ehr/app/src/types/types.ts
- packages/telemed-ehr/zambdas/src/get-appointments/index.ts
- packages/telemed-intake/zambdas/src/demo/example.spec.ts
- packages/telemed-intake/zambdas/src/get-schedule/index.ts
- packages/urgent-care-intake/app/src/api/zapehrApi.ts
- packages/urgent-care-intake/zambdas/src/shared/dateUtils.ts
https://github.com/masslight/ottehr/issues/548
> Demo button upgrades

- packages/telemed-ehr/app/src/helpers/create-sample-appointments.ts
Patients created via demo visits button are missing phone number in their credentials
> Add phone number to patient details

- packages/telemed-ehr/zambdas/src/get-appointments/index.ts
https://github.com/masslight/ottehr/issues/578
Makes sure to filter only in-person appointments for get-appointments zambda.
> Remove duplicate appointments

- packages/utils/lib/fhir/constants.ts
> Issue 735. EHR. Patient information. Docs. Uploaded insurance should be displayed in "Insurance Cards" instead of "Consent Forms" section

- apps/ehr/src/features/css-module/components/Header.tsx
- apps/ehr/src/features/css-module/components/vitals/weights/VitalWeightHistoryElement.tsx
- apps/ehr/src/features/css-module/components/vitals/weights/VitalWeightHistoryEntry.ts
- apps/ehr/src/features/css-module/components/vitals/weights/VitalsWeightsCard.tsx
- apps/ehr/src/features/css-module/components/vitals/weights/helpers.ts
- apps/ehr/src/telemed/features/appointment/AppointmentSidePanel.tsx
- packages/utils/lib/helpers/visit-note/map-vitals-to-display.helper.ts
- packages/utils/lib/helpers/vitals/vitals-weight.helper.ts
Link to issue #821 
Removed weight percentiles out of everywhere, removed weight from Telemed sidebar and in-person header
> Issue 821: Remove weight percentiles

- apps/ehr/src/components/PatientsSearch/utils/buildSearchQuery.ts
Fix for https://github.com/masslight/ottehr/issues/976
Appointemnts and corresponding Locations need to be queried every time despite `location` filter in order to correctly populate  "Last Visit" column.
> EHR. Patients search. Always query appointments and locations for "Last Visit" column

- packages/intake/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/helpers.ts
- packages/intake/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/index.ts
Fix for https://github.com/masslight/ottehr/issues/1037.
`Coverage.payor` needs to be updated when `insurance-carrier` is present in `QuestionnaireResponse`.
Did a small refactoring by deleting a shared `operation` variable as it's usage is very confusing.
> Update Coverage.payor when insurance provider is changed during paperwork

- packages/utils/lib/fhir/resourcePatch.ts
#1192
Fixed failing patch Patient resource with not defined `telecom` before harvesting.
> Issue 1192. Telemed. Error when clicking "Rx" button

- .husky/pre-commit
- .lintstagedrc.json
- apps/ehr/.lintstagedrc.json
- apps/intake/.lintstagedrc.json
- package-lock.json
- package.json
- packages/ehr/zambdas/.lintstagedrc.json
- packages/intake/zambdas/.lintstagedrc.json
- scripts/.lintstagedrc.json
A single top-level config file wasn't working, and lint-staged [recommends](https://github.com/lint-staged/lint-staged?tab=readme-ov-file#how-to-use-lint-staged-in-a-multi-package-monorepo) per-package config for monorepos. Also updates `husky` to a new version with a simplified interface.
> fix(dx): Update husky, per-project hook config

- apps/ehr/vite.config.ts
- apps/intake/vite.config.ts
- packages/ehr/zambdas/scripts/detect-tls.js
- packages/ehr/zambdas/scripts/setup.ts
- packages/ehr/zambdas/serverless.yml
- packages/intake/zambdas/scripts/detect-tls.js
- packages/intake/zambdas/scripts/setup-intake.ts
- packages/intake/zambdas/serverless.yml
This change supports developers working on a "remote development mode" setup, where they stand up Ottehr for testing or development in local "development mode" (`npm run apps:start`) on a remote server. The auth0 provider requires it be served over HTTPS when not on `localhost`, so these setups won't run without local TLS support.
#285
> feat: Add support for local TLS

- apps/ehr/src/telemed/features/appointment/PlanTab/components/PatientInstructionsTemplatesDialog.tsx
- apps/ehr/src/telemed/state/appointment/appointment.queries.ts
- packages/ehr/zambdas/src/delete-patient-instruction/index.ts
- packages/ehr/zambdas/src/delete-patient-instruction/validateRequestParameters.ts
- packages/ehr/zambdas/src/save-patient-instruction/index.ts
- packages/utils/lib/types/api/patient-instructions/patient-instructions.types.ts
When a zambda has `id` as a parameter it's impossible to execute it correctly as the `id` parameter clashes with zambda's `id` when executed using OystEHR's SDK `oystehr.zambda.execute` function.
Fix for https://github.com/masslight/ottehr/issues/956.
> Rename "id" parameter to "instructionId" for "delete-patient-instruction" and "save-patient-instruction" zambdas

- packages/ehr/zambdas/src/paperwork-to-pdf/index.ts
- packages/utils/lib/fhir/constants.ts
- packages/utils/lib/types/data/paperwork/paperwork.constants.ts
Implementation of https://github.com/masslight/ottehr/issues/1318
Exported questionnaire responses PDF are shown in "Patient docs" under "Exported questionnaires".
> Show exported questionnaire PDFs in patient docs explorer 

- apps/ehr/src/features/css-module/components/progress-note/ProgressNoteDetails.tsx
- packages/utils/lib/helpers/visit-note/create-vitals-search-config.helper.ts
- packages/utils/lib/helpers/visit-note/progress-note-chart-data-requested-fields.helper.ts
- packages/zambdas/src/ehr/sign-appointment/index.ts
#1713
fixed bug. also display section if notes added even if no observations shown, otherwise why add the note? e.g. "No vitals taken"
> fix bug, show section if note added

- .husky/post-commit
- .husky/pre-commit
#1804
my approach was:
1. stash staged changes only
2. stash everything else
3. pop staged-only stash
4. lint and stage everything as before because linting might fix and stage files
5. commit
6. pop non-staged files stash
> fix pre-commit hooks commits all files not just staged ones

- apps/ehr/src/features/external-labs/components/OrderCollection.tsx
- apps/ehr/src/features/external-labs/components/details/DetailsWithoutResults.tsx
- apps/ehr/src/features/external-labs/components/details/Questionarie.tsx
- packages/utils/lib/types/api/lab.ts
- packages/utils/lib/types/data/labs/labs.constants.ts
- packages/zambdas/src/ehr/get-create-lab-order-resources/validateRequestParameters.ts
- packages/zambdas/src/ehr/get-lab-order-details/index.ts
- packages/zambdas/src/ehr/shared/labs.ts
- packages/zambdas/src/ehr/submit-lab-order/index.ts
- packages/zambdas/src/ehr/submit-lab-order/validateRequestParameters.ts
- packages/zambdas/src/shared/pdf/types.ts
- packages/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/index.ts
We needed a solution asap to be able to test on staging, otherwise there was no good way for the FE to get the accountNumber which is necessary to submit the lab.
> Temp fix: add accountNumber to Org, update submit lab flow

- apps/ehr/playwright.config.ts
- apps/ehr/tests/e2e/specs/addPatientPage.spec.ts
- packages/zambdas/ottehr-spec.json
Zambda deploy script doesn't currently allow for zambdas to run on both create and update events. Temporarily setting the create-review-lab-results-task subscription zambda to "create" event to unblock QA while we update the zambda-deploy script
> Temp fix: Make create-review-lab-results-task run on "create" 

- packages/zambdas/src/patient/appointment/prebook-update-appointment/index.ts
#1239
---
there are 2 pending bugs:
1. modifying an apt sends the old start time in the confirmation email and message (this pr)
2. i believe sometimes the subscription is run before the appointment is created, so the fhir search fails and the confirmation email and message is never sent because the subscription fails. oystehr has fixed this and will be in the v1.22 release.
> fix update apt using old start time

- apps/ehr/tests/e2e/specs/telemed/assessmentTab.spec.ts
#971 was already partially covered in assessmentPage tests. 
It checks for missing card here and all required field links: https://vscode.dev/github/masslight/ottehr/blob/971/missing-section-tests/apps/ehr/tests/e2e/specs/telemed/assessmentTab.spec.ts#L63
A couple lines after, it clicks on the missing field link and it goes to Assessment page.
Here I added check that it's not visible if everything is filled in: https://vscode.dev/github/masslight/ottehr/blob/971/missing-section-tests/apps/ehr/tests/e2e/specs/telemed/assessmentTab.spec.ts#L254
> 971 missing section e2e tests

- packages/zambdas/ottehr-spec.json
This was impacting labs workflows when we would submit our QuestionnaireResponse. This change makes the criteria for this harvest zambda more specific to only trigger on harvest specific QRs
Tested on dev
> Fix: Make sub-harvest-intake zambda criteria more specific

- packages/zambdas/src/ehr/create-lab-order/index.ts
Changed from `routine` to `stat` per @IraLeontseva's comment on #1249
> Fix: update lab order creation priority

- apps/ehr/tests/e2e/specs/patientRecordPageInsuranceSection.spec.ts
Added missing step to test: save changes and refresh the page before checking updated info.
> Add missing step to "Update data from Insurance container" test

- scripts/run-e2e.ts
stop browser crashing when running e2e tests
> kill only node processes

- packages/zambdas/ottehr-spec.json
- packages/zambdas/src/scripts/deploy-zambdas.ts
#2006 
Previous deploy zambda script failed validation if an event was not passed into the ottehr spec for subscription zambda, but "no event" is the equivalent of saying the sub should run on both create and update (and matches the convention in the public docs). This tiny change enables that. 
Tested on dev with the handle-lab-result zambda (which should indeed run on both create and update). Confirmed that no extension for create or update was written to the Subscription.
> Feat: enable zambda subs to run on create&update (not XOR)

- apps/ehr/src/features/external-labs/components/details/DetailsWithoutResults.tsx
- packages/utils/lib/types/data/labs/labs.constants.ts
- packages/utils/lib/types/data/labs/labs.types.ts
- packages/zambdas/src/ehr/create-lab-order/index.ts
- packages/zambdas/src/ehr/get-lab-orders/helpers.ts
- packages/zambdas/src/ehr/submit-lab-order/index.ts
- https://github.com/masslight/ottehr/issues/2079
- patches specimen with collected by / datetime before submitting to oystehr
- adds an extension to specimen to link it back to the correct specimen definition
- removes orderSource from LabOrderDetailedPageDTO (wasn't being used)
> Update external lab order history table 

- packages/utils/lib/types/data/labs/labs.constants.ts
- packages/zambdas/src/ehr/create-lab-order/index.ts
- packages/zambdas/src/ehr/submit-lab-order/index.ts
We need to add a field to capture number of containers used for collection (we have a ticket to do this in the next iteration). For now we will just hard code it to 1 so there are no errors submitting the order to oystehr. 
We are still figuring out how to deal with the issue of not have a type - for now, hard coding this value at creation. This is just to facilitate testing.
> Temporarily hard coding type and container quantity on specimen

- apps/ehr/src/features/css-module/context/NavigationContext.tsx
- apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/SurgicalHistory/ProceduresForm.tsx
- apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/SurgicalHistory/ProceduresNoteField.tsx
- apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/SurgicalHistory/SurgicalHistoryProviderColumn.tsx
- apps/ehr/src/telemed/features/appointment/ReviewTab/components/SurgicalHistoryContainer.tsx
- apps/ehr/src/telemed/hooks/useChartDataArrayValue.ts
- apps/ehr/src/telemed/hooks/useDebounceNotesField.ts
- packages/utils/lib/types/api/chart-data/chart-data.types.ts
- packages/zambdas/src/ehr/delete-chart-data/index.ts
- packages/zambdas/src/ehr/get-chart-data/helpers.ts
- packages/zambdas/src/ehr/get-chart-data/index.ts
- packages/zambdas/src/ehr/save-chart-data/helpers.ts
- packages/zambdas/src/ehr/save-chart-data/index.ts
- packages/zambdas/src/shared/chart-data/index.ts
- packages/zambdas/src/shared/pdf/visit-details-pdf/visit-note-pdf-creation.ts
Refactor chart data to use "surgicalHistory" and "surgicalHistoryNote" for representing Surgical history related data instead of "procedure" and "procedureNote" to avoid clash with the new "Procedures" feature.
> Refactor chart data to use "surgicalHistory" for representing Surgical history data

- scripts/deploy/aws/bin/update-config.ts
- scripts/deploy/aws/deploy.sh
- scripts/deploy/gcp/deploy.sh
- scripts/deploy/package-lock.json
Having these out of order was causing an error when setting up secrets. The error was not easily visible as part of deploy execution without `set -e`.
> fix(deploy): Set up resources before secrets, fail on error

- packages/zambdas/src/shared/pdf/external-labs-results-form-pdf.ts
- packages/zambdas/src/shared/pdf/types.ts
Updates the result pdf header to be DR.status aware. Specifically relates to this issue https://github.com/masslight/ottehr/issues/1246#issuecomment-2877332324
> Fix: update lab pdf header

- apps/ehr/env/.env.local-template
- apps/ehr/src/api/api.ts
- apps/ehr/src/features/in-house-labs/components/details/CollectSampleView.tsx
- apps/ehr/src/features/in-house-labs/pages/InHouseLabOrderCreatePage.tsx
- apps/ehr/src/features/in-house-labs/pages/InHouseLabOrderDetailsPage.tsx
- packages/utils/lib/types/common.ts
- packages/zambdas/ottehr-spec.json
- packages/zambdas/src/ehr/get-or-create-visit-label-pdf/index.ts
- packages/zambdas/src/ehr/get-or-create-visit-label-pdf/validateRequestParameters.ts
- packages/zambdas/src/shared/pdf/external-labs-label-pdf.ts
- packages/zambdas/src/shared/pdf/visit-label-pdf.ts
#2152 
The visit label is general use and not specific to anything in house labs. However, it is used to label in house lab samples. Eventually, the getOrCreateVisitLabelPdf can easily be added to any other button in the UI that needs to pull up the visit label
Bug:
> Feat: add visit label, connect to in house labs

- apps/ehr/src/telemed/features/appointment/ReviewTab/components/ProceduresContainer.tsx
- packages/zambdas/src/shared/pdf/visit-note-pdf.ts
Fix for https://github.com/masslight/ottehr/issues/2484
> Procedures. Don't show 'Dx' and 'CPT' labels on Progress note if they were not filled on Procedures screen

- packages/zambdas/src/ehr/handle-in-house-lab-results/validateRequestParameters.ts
- packages/zambdas/src/ehr/submit-lab-order/index.ts
- packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts
- packages/zambdas/src/shared/pdf/pdf-utils.ts
- packages/zambdas/src/shared/pdf/types.ts
Handles #2362, #2184, and #2249
also #2482 
and #2158 
Rewrites the pdf for results to use the pdf library in ottehr
External labs
In-house labs
Multiple pages
> Various labs pdf improvements

- apps/ehr/src/features/css-module/routing/helpers.ts
- apps/ehr/src/features/external-labs/components/details/DetailsWithResults.tsx
- apps/ehr/src/features/external-labs/components/labs-orders/usePatientLabOrders.ts
Changes
- Added helper function to generate URLs for external lab orders
- Updated markTaskAsReviewed function to include appointmentId parameter across relevant components
- Modified navigation to redirect to external lab orders URL after marking task as reviewed
Ref: EHR. Labs. Click on "Mark as Reviewed" should automatically redirect user to the Labs table #2501
> [External Labs] navigation to redirect to external lab orders URL after marking task as reviewed

- apps/ehr/src/features/common/DetailPageContainer.tsx
- apps/ehr/src/features/common/ListViewContainer.tsx
Looks like changes in this commit https://github.com/masslight/ottehr/commit/fa8be55#diff-bfe2fbe9c3dd2856a6889275dbfed1fb1069248fa4de7a0e59e47c77b8abe37b to CSS layout caused the gutters for the labs screens to render incorrectly.
> Fix lab screen gutters 

- .github/workflows/e2e-intake.yml
Reverting to the approach where we retrieve user.json cache from the login step to avoid duplicate logins. The trade-off is that we won't refresh cache that's about to expire. Not critical, so I'll consider a better solution later.
> [E2E] prevent duplication logins

- apps/ehr/src/pages/PatientDocumentsExplorerPage.tsx
- apps/ehr/tests/e2e-utils/seed-data/seed-ehr-appointment-data.json
- packages/utils/lib/fhir/constants.ts
- packages/zambdas/src/scripts/setup-document-explorer.ts
#1942
- updated folder title photo IDs to match allowed to client bucket
- allowed re-uploading the same file to avoid user confusion when no visible action occurs
> EHR. Docs. Privacy Policy and Paperwork folders do not allow to upload docs

- .github/workflows/e2e-intake.yml
actions/cache/restore@v4 doesn't re-save the cache, so it doesn't conflict with actions/cache/save@v4
> [E2E] fix user.json update error

- .github/workflows/cache-user-json-to-main.yml
Receiver workflow that creates shared cache accessible by all feature branches.
1. Listen for dispatch events from feature branches
2. Decrypt `user.json` and save to main branch cache
3. Feature branches access via `restore-keys`
- `repository_dispatch` only works in default branch (GitHub limitation)
- Cache created in feature scope only accessible by that branch or main branch
- Cache created in main scope is accessible by all branches
AES-256 decryption, cleanup
sender PR: https://github.com/masslight/ottehr/pull/2887
ref: https://github.com/masslight/ottehr/issues/2893
> [E2E] Add cache receiver workflow for cross-branch user.json sharing

- .github/workflows/e2e-intake.yml
Share Playwright login tokens across feature branches to reduce CI login overhead.
1. Encrypt `user.json` after successful login
2. Send to main branch via `repository_dispatch`
3. Other feature branches reuse cached tokens
GitHub Actions cache scope: feature branch cache only visible to itself, main branch cache visible to all branches.
- AES-256 encryption with existing `DEPLOY_OTTEHR_KEY`
- Package pinned to commit hash for security
Receiver PR: https://github.com/masslight/ottehr/pull/2888
ref: https://github.com/masslight/ottehr/issues/2893
> [E2E] Add cross-branch user.json caching via encrypted dispatch

- apps/ehr/src/features/in-house-labs/components/details/CollectSampleView.tsx
Fixes: Collection time in Sample Collection screen is device local time
see "to improve" in this comment https://github.com/masslight/ottehr/issues/2910#issuecomment-3031376825
> Fix inhouse lab sample collection timezone

- apps/ehr/src/features/css-module/components/vitals/components/VitalsTextInputFiled.tsx
- apps/ehr/src/features/css-module/components/vitals/vision/VitalsVisionCard.tsx
- apps/ehr/src/features/css-module/components/vitals/vision/helpers.ts
- packages/utils/lib/fhir/vitals.ts
- packages/utils/lib/helpers/visit-note/map-vitals-to-display.helper.ts
- packages/utils/lib/types/api/chart-data/chart-data.types.ts
Ref: https://github.com/masslight/ottehr/issues/2913
- Added VitalsTextFreeInputField component for text input (replaces numeric-only inputs)
- Extended VitalsVisionObservationDTO with leftEyeVisionText and rightEyeVisionText fields
- Updated FHIR functions to store vision data as valueString instead of valueQuantity
- Added backward compatibility to read legacy numeric values and convert them to text
- All vision input fields (left eye, right eye, both eyes) now accept free text input
> add VitalsTextFreeInputField and update vision observation handling

- apps/ehr/src/telemed/features/appointment/PlanTab/ERxContainer.tsx
- packages/utils/lib/fhir/constants.ts
- packages/zambdas/src/subscriptions/medication-request/process-erx-resources/index.ts
This commit fixes https://github.com/masslight/ottehr/issues/3074
Currently there's no way to test the implementation since the erx functionality is blocked by the non-working request to https://erx-api.zapehr.com/v3/patient/... Here's the discussion of this issue https://masslight.slack.com/archives/C06JW8P5CD8/p1752064652257499
I would appreciate an early code review
> Fix ERX history

- apps/intake/src/pages/StartVirtualVisit.tsx
Before we weren't checking the availability of the location/state:
After the change:
> fix: operate in state button changes in patient side

- apps/ehr/src/telemed/features/appointment/ERX.tsx
Emit ERROR when a practitioner has missing data in the profile.
Emit ERROR is ERX checks are not finished within 30 seconds.
> DDI/DDA - Fix ERX stuck in LOADING state

- packages/zambdas/src/ehr/patient-payments/post/index.ts
You can test this with the stripe 3ds test cards from here https://docs.stripe.com/testing?testing-method=card-numbers
> fix(payment): throw if 3ds at payment time for now

- packages/zambdas/src/ehr/submit-lab-order/index.ts
- packages/zambdas/src/shared/pdf/external-labs-order-form-pdf.ts
- packages/zambdas/src/shared/pdf/types.ts
#3326 
Order submitted electronically w/ E-REQ line
Order submitted manually
> Feat: add e-req line to order form

- apps/ehr/src/components/patient/Header.tsx
add optional chaining to safely access latest appointment encounter
> [EHR] fix crash on patient info page if no appointment was opened

- apps/ehr/src/telemed/state/appointment/appointment.store.ts
https://github.com/masslight/ottehr/issues/3644
> [EHR. Telemed] 'Medical decision making' is shown as missing when 'Progress note' is opened from the 'Patient record'

- apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/MedicationCardField.tsx
- apps/ehr/tests/e2e/page/EditMedicationCard.ts
- apps/ehr/tests/e2e/specs/in-person/inHouseMedicationsPage.spec.ts
- Fixed https://github.com/masslight/ottehr/issues/3690
- Removed 'Select Route' selection. We don't have 'Select Route' option after this PR https://github.com/masslight/ottehr/pull/3621
- Updated const ROUTE, because 'Route of administration values' will be removed soon
- We have issue after this PR https://github.com/masslight/ottehr/pull/3621, that 'Route' field is cleared after saving, so I commented out this step until issue will be fixed and created a ticket https://github.com/masslight/ottehr/issues/3712
> E2E. In-house medications. Fix tests

- config/ottehr-spec.json
- scripts/ottehr-setup.ts
Resolves issues with the zambdas `create-discharge-summary` and `paperwork-to-pdf`, as well as potentially other related ones in the `discharge-summaries` and `exported-questionnaires` buckets
> Fix config

- apps/ehr/src/features/css-module/components/screening/AskThePatient.tsx
- apps/ehr/src/features/css-module/components/screening/useScreeningQuestionsHandler.ts
- apps/ehr/src/telemed/hooks/useDebounce.ts
- packages/utils/lib/types/data/screening-questions/utils.ts
Fixed several edge cases, main changes:
1 - Fast sequential note editing. Added a key to debounce so individual notes are saved, rather than canceling the saving of other notes as happened with the shared debounce
2 - Fixed UI flickering when quickly switching radio buttons
3 - Fixed the case when input and note change rapidly - in this case a general request is sent and data is not lost
4 - Simplified implementation, eliminated the need to track current requests by removing the general chart data refetch and doing selective chart data updates, simplified the useScreeningQuestionsHandler.ts structure
5 - More clearly separated and simplified data - now only react-hook-form is responsible for optimistic data updates, while chart data is updated only on successful saving or deletion of data …
> improve screening questions form handling

- config/ottehr-spec.json
---
hosted ottehr instances deployed using terraform use the wrong system so faxes are not working. my bad.
> fix fax system

- apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/ChiefComplaint/ChiefComplaintCard.tsx
- apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/ChiefComplaint/ChiefComplaintProviderColumn.tsx
When applying templates, the HPI text field was not getting updated due to this bug which says "if it already has a value, do not do anything in the use effect".
Also capitalize one letter I noticed.
> allow HPI fields to get a new value when set by template

- config/oystehr/ottehr-spec.json
- packages/zambdas/src/patient/ai-interview/start/index.ts
- packages/zambdas/src/scripts/deploy-zambdas.ts
- packages/zambdas/src/shared/ai.ts
- Update initial AI chat prompt.
- Set `ai-interview-summary` zambda timeout to 300 seconds and fix zambda's timeout setting during deploy.
- Use Sonnet 4 model.
> Improve AI chat

- apps/ehr/src/constants/data-test-ids.ts
- apps/ehr/src/features/in-house-labs/pages/InHouseLabOrderCreatePage.tsx
- apps/ehr/tests/e2e/page/OrderInHouseLabPage.ts
- apps/ehr/tests/e2e/specs/in-person/inHouseLabsPage.spec.ts
Earlier, `TEST_TYPE` was hardcoded to `'Flu A'`, which caused test failures when the list of tests didn’t include the `Flu A` option. The tests have been updated to select the first available test from the list and verify that the CPT code is autofilled correctly based on the selected test.
> E2E. Update in-house labs tests.

- apps/ehr/tests/e2e/specs/ehr.spec.ts
OTR-810
---
this entire test suite [has been flaky before](https://github.com/masslight/ottehr/pull/2625/files#diff-b20583be6cc85cbf2a69e83feed95de1ad24814b2889482e056a060f7a956adbL211), but is a lot more stable now. i'm marking the entire suite as flaky though
> mark all search tests as flaky

- apps/ehr/src/features/external-labs/components/OrderCollection.tsx
- packages/utils/lib/types/data/labs/labs.types.ts
- packages/zambdas/src/ehr/get-lab-orders/helpers.ts
OTR-672
Note, did not add to Reflex Detail view as we can't be sure which SR the reflex test came from, so we can't really pinpoint an ordering location
For orders made before Locations were required, we simply show nothing. So it is backwards compatible.
> Feat(labs): add ordering office info to order details

- apps/ehr/src/telemed/features/appointment/ERXDialog.tsx
#3207
**Visual updates:**
Added button in the top-right corner
_inline eRx iframe:_
_full screen mode:_
> Issue 3207. EHR. eRx - Allow opening eRx in full-screen mode

- apps/ehr/package.json
- apps/ehr/vite.config.ts
- apps/intake/package.json
- package.json
- packages/zambdas/package.json
Setup separate env for LabCorp testing so we don't change in-use resources in the ottehr envs. 
Secrets have been added to the ottehr secrets repo.
> Config: setup labcorp local env
