.vscode/Ottehr.code-workspace

just added a new package structure

fix package structure for workspace (#166)

---

packages/ottehr-components/lib/helpers/form/getFormInput.tsx
packages/telemed-intake/.gitignore
packages/telemed-intake/app/src/utils/paperworkCompleted.ts
packages/telemed-intake/zambdas/scripts/setup.ts
packages/telemed-intake/zambdas/src/get-schedule/index.ts
packages/telemed-intake/zambdas/src/paperwork/create-paperwork/index.ts
packages/telemed-intake/zambdas/src/paperwork/create-paperwork/validateRequestParameters.ts
packages/telemed-intake/zambdas/src/paperwork/get-paperwork/index.ts
packages/urgent-care-intake/zambdas/src/get-paperwork/index.ts
packages/utils/lib/helpers/paperwork/paperwork.helper.ts
packages/utils/lib/types/common.ts

```json
{
"id": "6df33c49-b9fa-4da8-a836-e7acd2784dcb",
"resourceType": "Questionnaire",
"name": "telemed",
"status": "draft",
"item": [
{
"linkId": "rnn-trial",
"text": "Need a refresher on Harbor's Remote Night Nanny?",
"type": "group",
"item": [
{
"linkId": "rnn-reminder-caption",
"text": "As a reminder you get a FREE extended trial with your presale purchase!",
"type": "display",
"extension": [
{
"url": "https://fhir.zapehr.com/r4/StructureDefinitions/text-type",
"valueString": "p"
}
]
},
{
"linkId": "rnn-reminder-video",
"text": "<div style=\"padding:56.25% 0 0 0;position:relative;\"><iframe src=\"https://player.vimeo.com/video/913424910?h=dfa236ec46&amp;badge=0&amp;autopause=0&amp;player_id=0&amp;app_id=58479\" frameborder=\"0\" allow=\"autoplay; fullscreen; picture-in-picture; …
```

Enables forms without documents & add an Html field

---

README.md

added DCO to readme

---

packages/ottehr-components/lib/components/CustomContainerFactory.tsx
packages/telemed-ehr/app/src/CustomThemeProvider.tsx
packages/telemed-ehr/app/src/pages/Appointments.tsx
packages/telemed-ehr/app/src/pages/Patients.tsx
packages/telemed-ehr/app/src/telemed/features/telemed-admin/EditState.tsx
packages/telemed-ehr/app/src/telemed/features/telemed-admin/Insurance.tsx
packages/telemed-intake/app/src/features/homepage/HomepageOption.tsx

Resized homepage icons, removed old colors from last year and fixed contrast text color for buttons

UI Improvements for the next release

---

README.md

setup instructions for Windows users

docs(README): Add setup instructions for Windows users

---

package.json
packages/telemed-intake/app/src/components/CallSettingsDialog/CallSettings.tsx
packages/telemed-intake/app/src/components/CallSettingsDialog/CameraSettings.tsx
packages/telemed-intake/app/src/components/CallSettingsDialog/MicrophoneSettings.tsx
packages/telemed-intake/app/src/components/CallSettingsDialog/SoundSettings.tsx
packages/telemed-intake/app/src/components/CallSettingsDialog/index.ts
packages/telemed-intake/app/src/features/invited-participants/InviteParticipantForm.tsx
packages/telemed-intake/app/src/features/invited-participants/ManageParticipants.tsx
packages/telemed-intake/app/src/features/upload-photos/UploadPhotosListItemButton.tsx
packages/telemed-intake/app/src/features/video-call/call-settings.store.ts
packages/telemed-intake/app/src/pages/WaitingRoom.tsx
packages/telemed-intake/app/src/utils/index.ts
packages/telemed-intake/app/src/utils/zustandDevtools.ts
pnpm-lock.yaml

Waiting room fixes

---

packages/telemed-ehr/app/src/helpers/create-sample-appointments.ts
packages/telemed-ehr/app/src/telemed/features/tracking-board/CreateDemoVisits.tsx
packages/telemed-intake/zambdas/src/appointment/create-appointment/index.ts

https://github.com/masslight/ottehr/issues/399

Fix get appointment 500 error

---

packages/telemed-ehr/app/src/pages/AppointmentPage.tsx
packages/telemed-ehr/app/src/telemed/features/appointment/AppointmentHeader.tsx
packages/telemed-ehr/app/src/telemed/pages/AppointmentPage.tsx

https://github.com/masslight/ottehr/issues/452

Appointment page close button

---

packages/telemed-ehr/app/src/helpers/create-sample-appointments.ts
packages/telemed-ehr/app/src/telemed/features/tracking-board/CreateDemoVisits.tsx

Fix for https://github.com/masslight/ottehr/issues/384

Sample visits phone number input refactor

---

packages/telemed-intake/app/src/pages/PatientPortal.tsx
packages/telemed-intake/app/src/pages/Welcome.tsx

Fix for https://github.com/masslight/ottehr/issues/449

Flow changes for new intake users

---

packages/telemed-intake/app/src/pages/AuthPage.tsx

https://github.com/masslight/ottehr/issues/470

Fix for redirect issue related to welcome path

---

packages/telemed-ehr/zambdas/scripts/setup.ts
packages/telemed-intake/zambdas/scripts/setup.ts

- Add project-id to intake environment variables setup
- Add school-work-note-templates to z3 bucket creation for ehr setup

Update setup scripts

---

packages/telemed-ehr/app/package.json

Related to https://github.com/masslight/ottehr/issues/527 and  https://github.com/masslight/ottehr/actions/runs/11554702751 
Removing unnecessary profile element resulted with successful deploy

Fix for ehr deploy script

---

packages/telemed-intake/app/src/features/patients/patients.queries.ts
packages/telemed-intake/app/src/pages/PatientPortal.tsx
packages/telemed-intake/app/src/pages/Welcome.tsx

Fixed the apiclient error for welcome and patient portal pages 
https://github.com/masslight/ottehr/issues/521
Added loading indicator for continue button for a better UX for welcome page
https://github.com/masslight/ottehr/issues/522

Fix for landing page errors

---

packages/ehr-utils/lib/types/user.types.ts
packages/telemed-ehr/app/package.json
packages/telemed-ehr/app/src/App.tsx
packages/telemed-ehr/app/src/components/EmployeeInformationForm.tsx
packages/telemed-ehr/app/src/types/types.ts
packages/telemed-ehr/zambdas/scripts/invite-user.ts
packages/telemed-ehr/zambdas/src/shared/accessPolicies.ts
packages/telemed-ehr/zambdas/src/shared/index.ts
pnpm-lock.yaml

added a prescriber role, added default phone number and NPI to default practitioner

added a brand new prescriber role 

---

packages/telemed-intake/app/src/features/video-call/video-call.queries.ts
packages/telemed-intake/app/src/pages/ReviewPaperwork.tsx
packages/telemed-intake/app/src/pages/VideoChatPage.tsx
packages/telemed-intake/app/vite.config.ts

Reverts masslight/ottehr#565 because it does not completely solve the problem

Revert "Videochat page updates"

---

packages/telemed-intake/app/src/features/video-call/video-call.queries.ts
packages/telemed-intake/app/src/pages/ReviewPaperwork.tsx
packages/telemed-intake/app/src/pages/VideoChatPage.tsx
packages/telemed-intake/app/vite.config.ts

Bring back "Videochat page updates""

---

packages/telemed-ehr/app/src/components/inputs/ProvidersSelect.tsx
packages/telemed-ehr/app/src/helpers/create-sample-appointments.ts
packages/telemed-ehr/app/src/hooks/useOttehrUser.tsx
packages/telemed-ehr/app/src/pages/Appointments.tsx
packages/telemed-ehr/app/src/telemed/features/tracking-board/CreateDemoVisits.tsx
packages/telemed-ehr/app/src/telemed/features/tracking-board/StateSelect.tsx
packages/telemed-ehr/app/src/telemed/features/tracking-board/TrackingBoardFilters.tsx
packages/telemed-ehr/app/src/telemed/features/tracking-board/TrackingBoardTable.tsx
packages/telemed-ehr/app/src/telemed/features/tracking-board/TrackingBoardTabs.tsx
packages/telemed-ehr/app/src/types/types.ts
packages/telemed-ehr/zambdas/src/get-appointments/index.ts
packages/telemed-intake/zambdas/src/demo/example.spec.ts
packages/telemed-intake/zambdas/src/get-schedule/index.ts
packages/urgent-care-intake/app/src/api/zapehrApi.ts
packages/urgent-care-intake/zambdas/src/shared/dateUtils.ts

Revert "Demo button upgrades"

---

packages/telemed-intake/zambdas/scripts/setup.ts

Revert "Videochat invite list error"

---

packages/telemed-ehr/app/src/components/inputs/ProvidersSelect.tsx
packages/telemed-ehr/app/src/helpers/create-sample-appointments.ts
packages/telemed-ehr/app/src/hooks/useOttehrUser.tsx
packages/telemed-ehr/app/src/pages/Appointments.tsx
packages/telemed-ehr/app/src/telemed/features/tracking-board/CreateDemoVisits.tsx
packages/telemed-ehr/app/src/telemed/features/tracking-board/StateSelect.tsx
packages/telemed-ehr/app/src/telemed/features/tracking-board/TrackingBoardFilters.tsx
packages/telemed-ehr/app/src/telemed/features/tracking-board/TrackingBoardTable.tsx
packages/telemed-ehr/app/src/telemed/features/tracking-board/TrackingBoardTabs.tsx
packages/telemed-ehr/app/src/telemed/pages/TrackingBoardPage.tsx
packages/telemed-ehr/app/src/types/types.ts
packages/telemed-ehr/zambdas/src/get-appointments/index.ts
packages/telemed-intake/zambdas/src/demo/example.spec.ts
packages/telemed-intake/zambdas/src/get-schedule/index.ts
packages/urgent-care-intake/app/src/api/zapehrApi.ts
packages/urgent-care-intake/zambdas/src/shared/dateUtils.ts

https://github.com/masslight/ottehr/issues/548

Demo button upgrades

---

packages/telemed-intake/app/src/features/appointments/appointment.store.ts
packages/telemed-intake/app/src/pages/ConfirmDateOfBirth.tsx
packages/telemed-intake/app/src/pages/PatientInformation.tsx
packages/telemed-intake/app/src/pages/Welcome.tsx
packages/telemed-intake/app/src/theme/ottehr/i18n-en.json
packages/telemed-intake/app/src/utils/checkSlotTime.ts
packages/telemed-intake/app/src/utils/index.ts

https://github.com/masslight/ottehr/issues/488

Past slot time selection handling

---

packages/telemed-intake/app/src/components/VideoControls.tsx

https://github.com/masslight/ottehr/issues/583

End call redirect issue

---

packages/ehr/zambdas/scripts/setup-default-locations.ts
packages/intake/zambdas/scripts/setup-default-locations.ts
packages/utils/lib/fhir/location.ts

Refactor location filtering functions to prevent location duplicates in setup script.

Refactor location filtering functions

---

apps/intake/src/helpers/redirects.ts
apps/intake/src/pages/PrebookVisit.tsx

https://github.com/masslight/ottehr/issues/732
Fixed back navigation to location selection when returning from the next step;
Fixed location title logic;
Refactor PrebookVisit components for improved code organization

Fixed navigation to location selection; PrebookVisit refactor

---

apps/ehr/src/telemed/features/appointment/ExamTab/ExamTab.tsx
apps/ehr/src/telemed/features/appointment/ReviewTab/components/ExaminationContainer.tsx
packages/ehr/zambdas/src/delete-chart-data/index.ts

Fix Telemed EHR bugs

---

apps/ehr/src/telemed/features/appointment/ReviewTab/ReviewAndSignButton.tsx

According to https://github.com/masslight/ottehr/issues/797#issuecomment-2612196023

Remove Review&Sign button when appointment in completed status

---

apps/intake/src/pages/WelcomeBack.tsx

Issue 676: Display "We are closed" when office is closed

---

apps/ehr/src/telemed/features/appointment/ReviewTab/components/ExaminationContainer.tsx

Issue 727: Add nose section for read only exam container

---

packages/utils/lib/helpers/visit-note/map-vitals-to-display.helper.ts

Issue 868: Fix weight and height conversion for PDF

---

apps/ehr/src/telemed/features/tracking-board/TrackingBoardTable.tsx
apps/ehr/src/telemed/features/tracking-board/TrackingBoardTableRow.tsx

Issue 484. EHR - Telemedicine appointments skeleton does not fill the section properly

---

apps/ehr/src/telemed/features/tracking-board/TrackingBoardTableRow.tsx

Issue 484/fix. Regression bug with tracking board columns.

---

apps/ehr/src/hooks/useGetPatientDocs.ts
apps/ehr/src/pages/PatientDocumentsExplorerPage.tsx

#854 
**Visual updates:**
[Screencast from 30.01.2025 16:52:32.webm](https://github.com/user-attachments/assets/f347a4ec-477b-4c87-9ed1-c8a73eef7668)

Issue 854. PMR. Docs. Automatically refresh Docs explorer after adding a doc

---

apps/ehr/src/api/api.ts
apps/ehr/src/telemed/components/CancelVisitDialog.tsx
packages/intake/zambdas/src/appointment/prebook-cancel-appointment/validateRequestParameters.ts
packages/utils/lib/types/urgent-care/common.ts

Issue 726. EHR. Virual visit. Cancel a visit failed

---

apps/intake/src/pages/Welcome.tsx

https://github.com/masslight/ottehr/issues/908

fix wrong welcome page redirect

---

.github/workflows/e2e-tests.yml
apps/ehr/src/components/AppointmentTableRow.tsx

https://github.com/masslight/ottehr/issues/947

[EHR] fix track-board navigation

---

packages/intake/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/helpers.ts
packages/intake/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/index.ts

Issue 989. EHR. Telemed eRX not working

---

packages/ehr/zambdas/src/shared/accessPolicies.ts

Update admin role to allow editing Group schedules and adding Providers to groups

Update admin role

---

packages/intake/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/helpers.ts

Issue 983. QRS. In-Person. Paperwork is NOT pre-populated with previously submitted patient data

---

apps/ehr/src/components/PatientsSearch/PatientsSearchFilters.tsx

Issue 910. EHR. Patient Search. DOB prepopulating with today's date bug

---

apps/ehr/src/pages/Appointments.tsx

Fix for https://github.com/masslight/ottehr/issues/750.

EHR. Appointments search. Use local timezone when location is not specified.

---

apps/intake/src/telemed/features/common/CustomContainer.tsx
packages/ui-components/lib/components/CustomContainerFactory.tsx

Fix for https://github.com/masslight/ottehr/issues/743

Fix "Oops!, something went wrong" error after clicking on Logout

---

apps/ehr/src/components/PatientEncountersGrid.tsx

Fix Visit Details accessed from Patient Record "Visit Info"

---

packages/ehr/zambdas/src/get-telemed-appointments/index.ts

Allows fetching telemedicine appointments even if some patient data has been deleted

Handle patient deletion case in telemed appointments retrieval

---

apps/intake/tests/specs/telemed/test.new-patient.spec.ts
apps/intake/tests/utils/auth/getAuth0Token.ts
apps/intake/tests/utils/resource-handler.ts
packages/ehr/zambdas/scripts/remove-test-patient-data.ts

fixed path to delete-appointment-data in remove-test-patient-data script, skipped test that fails on preconditions

Fix failing test in telemed

---

packages/zambda-utils/lib/lambda/index.ts

https://github.com/masslight/ottehr/issues/1152

Do not throw error when sendgrid email fails

---

apps/ehr/src/components/AppointmentTableRow.tsx
packages/ehr/zambdas/src/get-appointments/index.ts
packages/utils/lib/types/data/appointments/appointments.types.ts

Cherry picking fix for https://github.com/masslight/ottehr/issues/1127 from another unmerged branch

Fix intake button issue [cherry-pick]

---

apps/ehr/src/pages/Appointments.tsx

https://github.com/masslight/ottehr/issues/1169

Fixed timezone handling in appointments useEffect

---

apps/ehr/src/pages/Appointments.tsx

https://github.com/masslight/ottehr/issues/1209

fix appointment data hiding during the refreshes

---

.github/workflows/deploy-services.yml
apps/ehr/package.json
package-lock.json
packages/ehr/zambdas/package.json

Added if statements to deploy-script not to run version bump substeps when it was not checked and removed unnecessary steps

Fix version bump in deploy-services

---

apps/intake/src/helpers/data-test-ids.ts
apps/intake/src/pages/PrebookVisit.tsx
apps/intake/src/pages/ThankYou.tsx
apps/intake/tests/specs/telemed/test.book-virtual-visit.spec.ts
apps/intake/tests/specs/telemed/test.new-patient.spec.ts
apps/intake/tests/utils/utils.ts

#1033 created tests to check if patient can pre-book virtual visit with creating new patient

QRS. E2E. Schedule Virtual Visit

---

apps/ehr/src/components/CreateDemoVisits.tsx
apps/ehr/test/e2e-utils/resource-handler.ts
apps/ehr/test/e2e/specs/addPatientPage.spec.ts
packages/ehr/zambdas/scripts/remove-test-patient-data.ts
packages/utils/lib/helpers/create-prebook-demo-visits.ts
packages/utils/lib/helpers/create-telemed-demo-visits.ts
packages/utils/lib/helpers/helpers.ts
packages/utils/lib/helpers/index.ts

Fixed cleanup for patients in resource handler, fixed using patch paperwork and submit paperwork endpoints when creating appointments instead of direct fhir operations to closer match the patient flow by calling same endpoints

Fix e2e resource handlers and creating demo appts

---

apps/ehr/test/e2e-utils/resource-handler.ts
apps/ehr/test/e2e/page/PatientInfo.ts
apps/ehr/test/e2e/specs/inPersonVisitMainFlow.spec.ts

In-person flow e2e tests fix

---

apps/intake/src/pages/Review.tsx

fix timezone in walk-in review page

---

apps/ehr/test/e2e-utils/resource-handler.ts
apps/ehr/test/e2e/page/VisitsPage.ts
apps/ehr/test/e2e/specs/addPatientPage.spec.ts
apps/intake/src/telemed/pages/Homepage.tsx
apps/intake/tests/specs/in-person/Paperwork.spec.ts
apps/intake/tests/utils/Paperwork.ts
apps/intake/tests/utils/in-person/BaseInPersonFlow.ts
packages/ehr/zambdas/scripts/setup.ts
packages/test-utils/lib/e2e/clean-appointment.ts

1277 default group name change

---

apps/intake/src/pages/PastVisits.tsx
packages/intake/zambdas/src/appointment/get-past-visits/index.ts

sort past visits by descending date

---

apps/ehr/src/components/form/DatePicker.tsx
apps/ehr/src/components/form/FormAutocomplete.tsx
apps/ehr/src/components/form/FormSelect.tsx
apps/ehr/src/components/form/FormTextField.tsx
apps/ehr/src/components/patient/AboutPatientContainer.tsx
apps/ehr/src/components/patient/ActionBar.tsx
apps/ehr/src/components/patient/ContactContainer.tsx
apps/ehr/src/components/patient/InsuranceContainer.tsx
apps/ehr/src/components/patient/PatientDetailsContainer.tsx
apps/ehr/src/components/patient/PrimaryCareContainer.tsx
apps/ehr/src/components/patient/ResponsibleInformationContainer.tsx
apps/ehr/src/components/patient/SettingsContainer.tsx
apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/MedicationCardField.tsx
apps/ehr/src/hooks/useGetPatient.ts
packages/utils/lib/helpers/helpers.ts
packages/utils/lib/helpers/paperwork/validation.ts
packages/utils/lib/validation/constants.ts

#1153
Rebased from develop branch

Issue 1153. Issue 1153. EHR / Patient Information: Add validation error messages for missing filelds and wrong format

---

apps/ehr/src/App.tsx

fix patient docs not loading sometimes

---

apps/ehr/src/components/patient/ResponsibleInformationContainer.tsx

Issue-1338. EHR / Patient Information. Responsible party information (from QRS) is NOT displayed.

---

apps/ehr/src/state/patient.store.ts

Issue 1350. EHR / Patient information. "Save changes" button throughs error

---

apps/ehr/src/pages/Appointments.tsx
packages/ehr/zambdas/src/get-appointments/helpers.ts
packages/ehr/zambdas/src/get-appointments/index.ts

https://github.com/masslight/ottehr/issues/1355

fix timezone handling in appointments and encounters search

---

apps/intake/src/telemed/pages/SelectPatient.tsx

reset reason for visit when starting virtual visit

---

apps/ehr/src/hooks/useGetPatient.ts
apps/ehr/src/state/patient.store.ts

Issue 1378. EHR. Patient Information screen. Patient email and mobile are not saved

---

apps/ehr/src/components/form/FormSelect.tsx
apps/ehr/src/components/form/FormTextField.tsx
apps/ehr/src/components/patient/AddInsuranceModal.tsx
apps/ehr/src/components/patient/ContactContainer.tsx
apps/ehr/src/components/patient/InsuranceContainer.tsx
apps/ehr/src/components/patient/ResponsibleInformationContainer.tsx

Issue 1153. EHR / Patient Information: Add validation error messages for missing filelds and wrong format

---

apps/ehr/test/e2e-utils/resource-handler.ts
apps/ehr/test/e2e-utils/resource/in-house-medications.ts

help with setting up this automatic deletion

Automatic in-house orders deletion after tests

---

packages/ehr/zambdas/src/shared/pdf/visit-note-pdf.ts
packages/utils/lib/fhir/helpers.ts

https://github.com/masslight/ottehr/issues/903
before:
after:

[EHR] fix visit notes PDF

---

apps/intake/src/helpers/constants.ts
apps/intake/src/lib/i18n-en.json
apps/intake/src/lib/i18n-es.json
apps/intake/src/pages/Welcome.tsx
packages/ui-components/lib/i18n-en.json
packages/ui-components/lib/i18n-es.json

remove 'filling out as' from welcome page

---

apps/ehr/src/components/patient/ContactContainer.tsx

Issue 707. EHR. Contact Information. Need to add "Address Line 2" field

---

apps/ehr/src/components/CreateDemoVisits.tsx
apps/ehr/src/env.d.ts
apps/ehr/src/hooks/useAppClients.tsx

Part of #785 to support running in old way for this release

update env vars to support 785 task changes

---

apps/ehr/src/features/css-module/components/Header.tsx
apps/ehr/src/features/css-module/context/NavigationContext.tsx
apps/ehr/src/features/css-module/routing/CSSRouting.tsx
apps/ehr/test/e2e/specs/ehr.spec.ts

fixing mode state and route preserving 1143

---

packages/utils/lib/helpers/paperwork/prepopulation.ts

Issue 1515. QRS. Payment screen should have none option selected by default

---

packages/utils/lib/helpers/paperwork/prepopulation.ts

Issue 1514. QRS. Responsible party information - Birth sex shouldn't be preselected by default

---

apps/ehr/src/components/patient/PrimaryCareContainer.tsx
apps/ehr/src/state/patient.store.ts
packages/intake/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/helpers.ts
packages/utils/lib/fhir/resourcePatch.ts

Issue 1517. PCP phone number is pre-filled with incorrect number. It causes "not opening Visit Details page" issue

---

apps/intake/tests/specs/in-person/Paperwork.spec.ts
apps/intake/tests/utils/Paperwork.ts

https://github.com/masslight/ottehr/issues/851

QRS. E2E. Consent forms tests

---

packages/intake/zambdas/src/shared/appointment/helpers.ts
packages/utils/lib/fhir/resourcePatch.ts

Issue 1517. PCP phone number is pre-filled with incorrect number.

---

apps/intake/src/features/paperwork/useFormHelpers.tsx

#1573 
revert 9a9fd0d758b09ed092b267b256d6f04a6cab3dd2

Issue 1573. QRS. Paperwork - After removing secondary insurance, user can't continue flow

---

apps/ehr/tests/e2e/specs/telemed/telemedEhrFlow.spec.ts

Issue 929: Add zoomed condition photo check

---

apps/intake/src/helpers/data-test-ids.ts
apps/intake/src/pages/ReviewPaperwork.tsx
apps/intake/tests/specs/in-person/Paperwork.spec.ts
apps/intake/tests/specs/in-person/PaperworkReviewScreen.spec.ts
apps/intake/tests/utils/Paperwork.ts
apps/intake/tests/utils/in-person/BaseInPersonFlow.ts
apps/intake/tests/utils/locators.ts
packages/ui-components/lib/helpers/form/boolean.helper.tsx
packages/ui-components/lib/types/form/review-item-type.ts

- https://github.com/masslight/ottehr/issues/852
- Uncommented skipped tests after https://github.com/masslight/ottehr/issues/1515 and https://github.com/masslight/ottehr/issues/1514 fixes

QRS. E2E. Paperwork - Review and Submit

---

packages/zambdas/src/ehr/create-lab-order/index.ts

https://github.com/masslight/ottehr/issues/1414

map location to sr in create-lab-order

---

apps/intake/tests/specs/in-person/Paperwork.spec.ts
apps/intake/tests/specs/telemed/PaperworkTelemed.spec.ts
apps/intake/tests/utils/Paperwork.ts
apps/intake/tests/utils/UploadImage.ts
apps/intake/tests/utils/locators.ts

https://github.com/masslight/ottehr/issues/1667

QRS. E2E. Telemed - Patient condition

---

packages/utils/lib/deployed-resources/questionnaires/virtual-intake-questionnaire.json

Issue 1486. QRS. Secondary insurance. Fix options for "Patient's relationship to insured" field

---

apps/ehr/src/features/css-module/components/InternalNotes.tsx
apps/ehr/src/features/css-module/components/medication-administration/MedicationNotes.tsx
apps/ehr/src/features/css-module/components/patient-info/VitalsNotesCard.tsx
apps/ehr/src/features/css-module/components/screening/ASQ.tsx
apps/ehr/src/features/css-module/components/screening/AskThePatient.tsx
apps/ehr/src/features/css-module/components/screening/ScreeningNotes.tsx
apps/ehr/src/features/css-module/hooks/useIntakeNotes.tsx
apps/ehr/src/features/css-module/hooks/useInternalNotes.tsx
apps/ehr/src/features/css-module/pages/Screening.tsx
packages/utils/lib/fhir/uri.ts
packages/utils/lib/helpers/visit-note/create-vitals-search-config.helper.ts
packages/utils/lib/helpers/visit-note/progress-note-chart-data-requested-fields.helper.ts
packages/zambdas/src/ehr/get-chart-data/index.ts

https://github.com/masslight/ottehr/issues/1688
Fixed screening page loading issues, added well-typed _tag search param to chart data requests and made related change to code

Fix screening page in chart

---

apps/ehr/tests/e2e/specs/patientRecordPage.spec.ts

Part of https://github.com/masslight/ottehr/issues/1299

 EHR. E2E. Patient record. Patient information section - Updating values

---

apps/ehr/src/features/css-module/components/hospitalization/HospitalizationPatientComponent.tsx
apps/ehr/src/features/css-module/components/progress-note/HospitalizationContainer.tsx
apps/ehr/src/features/css-module/components/progress-note/ProgressNoteDetails.tsx
apps/ehr/src/telemed/features/appointment/ReviewTab/VisitNoteCard.tsx
apps/ehr/src/telemed/features/appointment/ReviewTab/components/AllergiesContainer.tsx
apps/ehr/src/telemed/features/appointment/ReviewTab/components/MedicalConditionsContainer.tsx
apps/ehr/src/telemed/features/appointment/ReviewTab/components/MedicationsContainer.tsx
apps/ehr/src/telemed/features/appointment/ReviewTab/components/SurgicalHistoryContainer.tsx
packages/zambdas/src/shared/pdf/visit-note-pdf.ts

Add label to progress notes when empty

---

apps/intake/tests/specs/telemed/PaperworkTelemed.spec.ts
apps/intake/tests/utils/CommonLocatorsHelper.ts
apps/intake/tests/utils/Paperwork.ts
apps/intake/tests/utils/locators.ts
apps/intake/tests/utils/telemed/Paperwork.ts

https://github.com/masslight/ottehr/issues/1689

QRS. E2E. Telemed - Would you like someone to join this call

---

packages/zambdas/src/ehr/shared/harvest/index.ts

#943
fixing regression caused by lost changes

bring back changes lost in merge

---

apps/ehr/src/constants/index.ts
packages/utils/lib/fhir/patientMasterRecord.ts
packages/utils/lib/helpers/paperwork/prepopulation.ts
packages/zambdas/src/ehr/shared/harvest/index.ts

Issue 1700. EHR. Patient Information screen. "Patient details" container fields should be pre-filled with entered data from QRS

---

packages/zambdas/src/patient/join-call/index.ts
packages/zambdas/src/patient/video-chat-invites/create-invite/index.ts

Issue 1386: Fix invite participant bug

---

apps/ehr/src/features/css-module/layout/CSSLayout.tsx

fixing https://github.com/masslight/ottehr/issues/1709

Fixed loading exams in provider charts

---

apps/ehr/src/components/patient/PrimaryCareContainer.tsx

Issue 1707. EHR. Patient Information screen. Error when updating data several times without refreshing the page

---

packages/zambdas/src/patient/appointment/get-past-visits/index.ts

Resolves https://github.com/masslight/ottehr/issues/1711

Past visits regression fix

---

packages/utils/lib/fhir/helpers.ts
packages/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/index.ts

bring back revinclude lists

---

packages/utils/lib/helpers/paperwork/prepopulation.ts
packages/zambdas/src/ehr/shared/harvest/index.ts

Issue 1708. EHR. Patient Information screen. "Responsible party information" fields are not pre-filled if patient selects "Self" option in QRS flow

---

packages/utils/lib/helpers/paperwork/prepopulation.ts

Issue 1575. EHR. Patient information. PCP name is not displayed

---

apps/ehr/src/components/patient/PatientDetailsContainer.tsx

Issue 1701. EHR. Patient Information screen. "Patient details" container. Selected values are not saved

---

apps/intake/tests/specs/telemed/PaperworkTelemedReviewScreen.spec.ts
apps/intake/tests/utils/Paperwork.ts
apps/intake/tests/utils/locators.ts
apps/intake/tests/utils/telemed/BaseTelemedFlow.ts
apps/intake/tests/utils/telemed/FillingInfo.ts
apps/intake/tests/utils/telemed/Paperwork.ts
apps/intake/tests/utils/telemed/PrebookTelemedFlow.ts

https://github.com/masslight/ottehr/issues/1740

QRS. E2E. Telemed - Review and submit

---

scripts/deploy/.gitignore
scripts/deploy/gcp/deploy.sh
scripts/deploy/package-lock.json
scripts/deploy/package.json

- deploy dir has its own npm module and deps
- use pushd/popd instead of managing relative paths
- upgrade ts to match rest of monorepo

fix(deploy/gcp): Install deps, pathing, ts version

---

apps/ehr/src/telemed/features/tracking-board/LocationSelect.tsx
apps/ehr/src/telemed/features/tracking-board/TrackingBoardFilters.tsx
apps/ehr/src/telemed/features/tracking-board/TrackingBoardTabs.tsx
apps/ehr/src/telemed/state/tracking-board/tracking-board.queries.ts
apps/ehr/src/telemed/state/tracking-board/tracking-board.store.ts
apps/ehr/src/telemed/utils/appointments.ts
packages/utils/lib/types/data/appointments/appointments.types.ts
packages/zambdas/src/ehr/get-telemed-appointments/helpers/fhir-resources-filters.ts
packages/zambdas/src/ehr/get-telemed-appointments/helpers/fhir-utils.ts
packages/zambdas/src/ehr/get-telemed-appointments/index.ts
packages/zambdas/src/ehr/get-telemed-appointments/validateRequestParameters.ts

Added telemed tracking board additional locations filtering based on the location in the `appointment.participant` property

Telemed additional locations filtering

---

apps/ehr/src/features/external-labs/components/details/Questionarie.tsx
apps/ehr/src/features/external-labs/pages/CreateExternalLabOrder.tsx
apps/ehr/src/telemed/features/appointment/AssessmentTab/components/DiagnosesContainer.tsx
packages/utils/lib/types/api/chart-data/chart-data.types.ts
packages/utils/lib/types/data/labs/labs.constants.ts
packages/zambdas/src/shared/chart-data/index.ts

https://github.com/masslight/ottehr/issues/1226

Update dx from orders pg

---

packages/zambdas/src/ehr/create-lab-order/index.ts

https://github.com/masslight/ottehr/issues/1763

Sr.insurance coverage should be active

---

packages/zambdas/src/ehr/create-lab-order/index.ts

https://github.com/masslight/ottehr/issues/1603

Map loincs to SR.code in create-lab-order

---

.husky/post-commit
.husky/pre-commit

#1804 
broke it further. undoing.

Revert "Merge pull request #1805 from masslight/omar/fix-pre-commit"

---

apps/ehr/README.md
apps/ehr/src/constants/feature-flags.ts
apps/ehr/src/features/css-module/routing/routesCSS.tsx
apps/ehr/src/pages/PatientPage.tsx

for enabling the env variable should be added:
VITE_APP_IS_LAB_ORDERS_ENABLED_FEATURE_FLAG=true

Add feature flag for lab orders

---

apps/ehr/src/hooks/useGetPatientDocs.ts
packages/zambdas/src/scripts/setup-document-explorer.ts

#1164
- Fixed the folder identification logic to properly match on UDI identifier value
- Added cleanup function to detect and remove duplicated List resources before updating folders
- Updated UI to display file extensions

Issue 1164/fix. Allow 'Upload Docs' to work for all existing patients.

---

packages/utils/lib/fhir/constants.ts
packages/zambdas/src/patient/telemed-get-patients/index.ts
packages/zambdas/src/patient/video-chat-invites/create-invite/index.ts
packages/zambdas/src/shared/appointment/helpers.ts

Issue 1737. EHR - Patient Info - Preferred Name Not Displayed

---

packages/utils/lib/helpers/paperwork/tests/recursive-group-transform.test.ts
packages/zambdas/src/ehr/shared/harvest/index.ts
packages/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/tests/data/base-qr.json
packages/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/tests/data/expected-coverage-resources-qr1.ts
packages/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/tests/harvest-module.test.ts
packages/zambdas/test/data/quetionnaire-responses.json

Issue 1756. EHR. Patient Information. Missing Insurance middle name from QRS

---

apps/ehr/src/components/PatientEncountersGrid.tsx

fix pre-booked telemed progress notes

---

apps/ehr/src/pages/AppointmentPage.tsx
apps/ehr/src/telemed/features/patient-visit-details/components/CompletedFormsContainer.tsx
apps/ehr/src/types/types.ts
apps/intake/tests/specs/in-person/Paperwork.spec.ts
apps/intake/tests/specs/telemed/PaperworkTelemed.spec.ts
packages/utils/lib/deployed-resources/questionnaires/in-person-intake-questionnaire.json
packages/utils/lib/deployed-resources/questionnaires/virtual-intake-questionnaire.json
packages/zambdas/src/ehr/shared/harvest/index.ts

fix missing 'get pdf' buttons

---

apps/ehr/src/telemed/features/appointment/ReviewTab/components/ExaminationContainer.tsx

fix missing nose comment in telemed

---

apps/ehr/tests/e2e-utils/resource/employees.ts

remove gmail from e2e tests

---

packages/zambdas/src/shared/pdf/visit-note-pdf.ts

remove 'recorded'

---

apps/ehr/src/pages/PatientDocumentsExplorerPage.tsx

#1164 
Added validation to prevent uploading files with symbols not supported by the Z3 Object.

Issue 1164. Allow 'Upload Docs' to work for all existing patients.

---

apps/ehr/src/components/form/DatePicker.tsx
apps/ehr/src/components/patient/AboutPatientContainer.tsx
apps/ehr/src/components/patient/AddInsuranceModal.tsx
apps/ehr/src/components/patient/InsuranceContainer.tsx
apps/ehr/src/components/patient/ResponsibleInformationContainer.tsx
apps/ehr/src/components/patient/SettingsContainer.tsx

Issue 1914. EHR: Patient Information - Responsible party younger 18 - add validation message

---

packages/utils/lib/fhir/helpers.ts

fix invalid uuid if full url used

---

README.md
scripts/deploy/aws/deploy.sh
scripts/deploy/gcp/deploy.sh

fix(deploy): Execute setup scripts directly

---

apps/ehr/tests/e2e/specs/telemed/telemedEhrFlow.spec.ts

Hotfix for few sms appeared in sms telemed e2e test

---

packages/zambdas/src/ehr/get-create-lab-order-resources/index.ts

Validate patient account has guarantor when loading create lab order

---

apps/intake/tests/specs/in-person/ScheduleModifyCancelInPersonVisit.spec.ts
packages/utils/lib/fhir/patient.ts
packages/zambdas/src/scripts/delete-appointment-data.ts

Added optimistic locking patches to Person resource in create appointment calls and e2e tests cleanup script

Person resource optimistic locking on updates

---

apps/ehr/src/components/patient/PrimaryCareContainer.tsx
apps/ehr/src/pages/PatientInformationPage.tsx

#1820 #1865 #1867
---
all fields in pcp info should be required if they're active

validate pcp form fields in patient info page

---

apps/ehr/src/features/external-labs/components/details/DetailsWithResults.tsx
apps/ehr/src/features/external-labs/components/details/PrelimCardView.tsx
apps/ehr/src/features/external-labs/components/details/ResultItem.tsx
packages/zambdas/src/ehr/get-lab-orders/helpers.ts
packages/zambdas/src/ehr/update-lab-order-resources/index.ts

https://github.com/masslight/ottehr/issues/1951

fix request for mark as reviewed #1951

---

apps/ehr/src/components/patient/PatientDetailsContainer.tsx

Issue 1815. EHR. Patient Information screen. Issues when "Other" option is selected in "Gender Identity" field.

---

apps/intake/src/features/paperwork/components/CreditCardVerification.tsx
apps/intake/src/helpers/data-test-ids.ts
apps/intake/tests/specs/in-person/PaperworkExisitingPatientSelf.spec.ts
apps/intake/tests/specs/in-person/PaperworkExistingPatient.spec.ts
apps/intake/tests/utils/Paperwork.ts
apps/intake/tests/utils/in-person/BaseInPersonFlow.ts
apps/intake/tests/utils/in-person/FillingInfo.ts
apps/intake/tests/utils/in-person/PrebookInPersonFlow.ts
apps/intake/tests/utils/in-person/StartInPersonFlow.ts
apps/intake/tests/utils/locators.ts

https://github.com/masslight/ottehr/issues/1855

QRS. E2E. In person - Tests to check that paperwork is prefilled for existing patient

---

packages/utils/lib/helpers/paperwork/prepopulation.ts

Issue 1822. EHR. Patient Information. Policy holder's sex - Intersex option not saved

---

apps/ehr/src/features/external-labs/components/OrderCollection.tsx
apps/ehr/src/features/external-labs/pages/CreateExternalLabOrder.tsx
packages/zambdas/src/ehr/create-lab-order/index.ts

- fixes bug opening labs without aoes from labs table
- fixes implementation bug where we are erroneously creating activity definitions that only need to be stored in serviceRequest.contained

fixes some labs bugs

---

README.md
apps/ehr/README.md

Update README files to correct links

---

apps/ehr/src/components/patient/PatientDetailsContainer.tsx
apps/ehr/src/constants/data-test-ids.ts
apps/ehr/tests/e2e/page/PatientInformationPage.ts
apps/ehr/tests/e2e/specs/patientRecordPage.spec.ts

https://github.com/masslight/ottehr/issues/1831

EHR. E2E. Patient record. Patient information - Patient details section - Cases when "Other" gender is selected

---

apps/ehr/src/telemed/features/telemed-admin/EditInsurance.tsx
apps/ehr/src/telemed/features/telemed-admin/Insurance.tsx
apps/ehr/src/telemed/features/telemed-admin/telemed-admin.queries.tsx
packages/zambdas/package.json
packages/zambdas/src/scripts/update-insurances-and-payer-orgs.ts

Fixing https://github.com/masslight/ottehr/issues/1009, https://github.com/masslight/ottehr/issues/1007, EHR part of https://github.com/masslight/ottehr/issues/1827

hide insurance settings, load all insurances in ehr

---

packages/zambdas/src/ehr/shared/labs.ts
packages/zambdas/src/ehr/submit-lab-order/helpers.ts
packages/zambdas/src/ehr/submit-lab-order/index.ts
packages/zambdas/src/shared/pdf/external-labs-order-form-pdf.ts

Submit and pdf generation needs to be able to work in cases where there is no AOE, as some orders do not have them.

Fix: Make labs AOE QuestionnaireResponse optional

---

apps/ehr/src/components/ScheduleInformation.tsx

Fix for https://github.com/masslight/ottehr/issues/1961
[screen-capture.webm](https://github.com/user-attachments/assets/12bc8581-3367-4b54-8164-4bdc55694295)

Always refresh "Schedules" page when opened

---

apps/ehr/tests/e2e/page/PatientInformationPage.ts
apps/ehr/tests/e2e/specs/patientRecordPage.spec.ts

https://github.com/masslight/ottehr/issues/1868

E2E. EHR. Patient information - Primary Care Physician section. Add validation error for invalid mobile

---

apps/ehr/tests/e2e/specs/patientRecordPage.spec.ts

https://github.com/masslight/ottehr/issues/1867

EHR. E2E. Patient information - Primary Care Physician section - All fields are required when checkbox is unmarked

---

packages/zambdas/src/patient/get-answer-options/index.ts

Issue 1827: Fix intake insurance plans

---

packages/zambdas/src/ehr/shared/harvest/index.ts

Issue 2008. QRS - Harvest module fails if "use": "official" is removed from FHIR Patient resource

---

packages/zambdas/src/shared/pdf/school-work-note-pdf.ts

fix broken excuse note bug

---

apps/ehr/src/components/EmployeeInformation/BasicInformation.tsx
apps/ehr/src/components/PhoneSearch.tsx
apps/ehr/src/components/dialogs/EditPatientDialog.tsx
apps/ehr/src/pages/AddPatient.tsx
apps/ehr/tests/e2e/page/AddPatientPage.ts
apps/intake/src/lib/i18n-en.json
packages/ui-components/lib/i18n-en.json

update phone validation error messages

---

packages/zambdas/package.json
packages/zambdas/src/scripts/reflex-test-helper.ts

to facilitate testing of https://github.com/masslight/ottehr/issues/2026 (and just general reflex test testing)

Mock reflex tests script

---

apps/ehr/src/pages/SchedulePage.tsx

fix new schedule changing active status

---

apps/ehr/src/features/external-labs/components/details/FinalCardView.tsx
packages/zambdas/src/ehr/get-lab-orders/helpers.ts

https://github.com/masslight/ottehr/issues/2091
hided panel if it's empty
removed 'who' from received history

fixed empty UI block; fixed display of received by #2091

---

apps/ehr/src/telemed/features/appointment/PlanTab/DispositionCard.tsx
apps/ehr/src/telemed/features/appointment/ReviewTab/components/PatientInstructionsContainer.tsx
apps/ehr/src/telemed/utils/disposition.helper.ts
packages/utils/lib/types/api/chart-data/chart-data.types.ts
packages/zambdas/src/shared/chart-data/index.ts
packages/zambdas/src/shared/pdf/types.ts
packages/zambdas/src/shared/pdf/visit-details-pdf/visit-note-pdf-creation.ts
packages/zambdas/src/shared/pdf/visit-note-pdf.ts

Issue 1712: Fix disposition section bugs

---

packages/zambdas/src/ehr/shared/harvest/index.ts

Issue 1823. EHR. Patient Information. Primary Insurance disappear after changing it to secondary. 

---

apps/ehr/src/features/external-labs/components/OrderCollection.tsx
apps/ehr/src/features/external-labs/components/OrderHistoryCard.tsx

https://github.com/masslight/ottehr/issues/2054

Fix date time display in lab order history 

---

packages/utils/lib/types/data/labs/labs.constants.ts

Adding new task type to facilitate corrected orders work

Feat: update lab order task definition for RCRT

---

apps/ehr/package.json
apps/ehr/src/components/patient/AddInsuranceModal.tsx
apps/ehr/src/constants/data-test-ids.ts
apps/ehr/src/pages/PatientInformationPage.tsx
apps/ehr/tests/e2e/page/PatientInformationPage.ts
apps/ehr/tests/e2e/page/patient-information/AddInsuranceDialog.ts
apps/ehr/tests/e2e/specs/patientRecordPageAddInsuranceDialog.spec.ts
apps/ehr/tests/e2e/specs/patientRecordPageInsuranceSection.spec.ts

https://github.com/masslight/ottehr/issues/1307

EHR. E2E. Patient record. Patient information - Insurance Information section. Add insurance

---

apps/ehr/tests/e2e/page/patient-information/AddInsuranceDialog.ts
apps/ehr/tests/e2e/specs/patientRecordPageAddInsuranceDialog.spec.ts

Adding Secondary insurance. All data is saved and displayed correctly.

EHR. E2E. Patient record. Patient information - Insurance Information section. Add Secondary insurance

---

apps/intake/tests/specs/in-person/PaperworkExistingPatient.spec.ts
apps/intake/tests/specs/telemed/PaperworkTelemedExistingPatient.spec.ts

Issue 1987. QRS. Insurance details - Policy holder's birth sex has incorrect value when Intersex was selected for previous visit

---

apps/ehr/src/api/api.ts
apps/ehr/src/features/external-labs/components/OrderCollection.tsx
apps/ehr/src/features/external-labs/pages/CreateExternalLabOrder.tsx
packages/utils/lib/types/errors/index.ts
packages/zambdas/src/ehr/create-lab-order/index.ts
packages/zambdas/src/ehr/create-lab-order/validateRequestParameters.ts
packages/zambdas/src/ehr/get-create-lab-order-resources/index.ts
packages/zambdas/src/ehr/get-create-lab-order-resources/validateRequestParameters.ts
packages/zambdas/src/ehr/submit-lab-order/index.ts
packages/zambdas/src/ehr/submit-lab-order/validateRequestParameters.ts

https://github.com/masslight/ottehr/issues/2111

Handle external labs error better

---

README.md
apps/ehr/tests/e2e-readme/README.md
apps/intake/tests/e2e-readme/README.md

fix more README links 

---

.github/workflows/deploy-services.yml

❇️ Quality of Life ❇️ 
No more digging through the logs to figure out which deploy run was for which env

Feat: Add env to deploy service job name

---

apps/ehr/src/features/external-labs/components/OrderCollection.tsx
apps/ehr/src/features/external-labs/components/SampleCollectionInstructionsCard.tsx

https://github.com/masslight/ottehr/issues/2119

Don't show aoe sections when there are no questions

---

packages/zambdas/src/ehr/submit-lab-order/index.ts

Fix: add check to avoid reducing empty specimens

---

packages/utils/lib/types/data/labs/labs.constants.ts
packages/zambdas/src/ehr/create-lab-order/index.ts
packages/zambdas/src/ehr/submit-lab-order/index.ts

To be merged after kunafa-hotfix-4 is released 
reverts https://github.com/masslight/ottehr/pull/2181

remove hard coded temp fix

---

apps/ehr/src/hooks/useGetPatient.ts

Issue 1965 / fix. EHR. Patient information - Insurance Information section. Insurance Carrier field isn't pre-filled

---

packages/utils/lib/helpers/paperwork/prepopulation.ts

Issue-1938. QRS. In-Person/Virtual. Insurance screen. Secondary insurance fields are pre-filled with incorrect data.

---

apps/intake/src/pages/WalkinLanding.tsx

Resolves https://github.com/masslight/ottehr/issues/2194

Project name regression

---

apps/intake/src/features/patients/components/selectable-list.tsx
apps/intake/src/pages/MyPatients.tsx

resolves https://github.com/masslight/ottehr/issues/722#issuecomment-2875234278

Fix for past visits no patients case

---

scripts/ottehr-setup.ts

update fax access policy in setup script

---

packages/utils/lib/fhir/helpers.ts
packages/utils/lib/types/data/labs/labs.constants.ts
packages/zambdas/src/shared/pdf/external-labs-results-form-pdf.ts

https://github.com/masslight/ottehr/issues/2233

Fix result pdf superseded bug

---

packages/zambdas/src/ehr/get-lab-orders/helpers.ts
packages/zambdas/src/scripts/reflex-test-helper.ts
packages/zambdas/src/shared/pdf/external-labs-results-form-pdf.ts

https://github.com/masslight/ottehr/issues/2274

Only grab current docRefs for labs results pdfs

---

packages/zambdas/src/ehr/submit-lab-order/index.ts

https://github.com/masslight/ottehr/issues/2190

Fix specimen patch request

---

apps/ehr/src/features/external-labs/components/ExternalLabsStatusChip.tsx
apps/ehr/src/features/external-labs/components/OrderHistoryCard.tsx

status history issue #2209

---

apps/ehr/src/telemed/features/appointment/ReviewTab/SendFaxButton.tsx
packages/zambdas/src/shared/validateBundleAndExtractAppointment.ts

this function is only used during the appointment cancellation zambdas, and thus would only be discovered during cancellation email flow
---
accidentally used #2303 as base branch

fix schedule bug

---

packages/zambdas/src/shared/pdf/visit-note-pdf.ts

https://github.com/masslight/ottehr/issues/1380

Remove audio video notes from in person visit notes

---

apps/ehr/src/features/css-module/pages/Procedures.tsx
apps/ehr/src/features/css-module/pages/ProceduresNew.tsx
apps/ehr/src/features/css-module/routing/routesCSS.tsx
packages/zambdas/src/shared/chart-data/index.ts

Part of https://github.com/masslight/ottehr/issues/1976

Procedure editing

---

packages/zambdas/src/shared/pdf/external-labs-results-form-pdf.ts

results info bugs #2270

---

apps/ehr/src/features/in-house-labs/components/details/ResultsEntryTableRow.tsx
packages/utils/lib/helpers/in-house-labs/index.ts
packages/utils/lib/types/data/in-house/in-house.types.ts
packages/zambdas/src/scripts/load-in-house-labs-tests.ts

Fix/feat: add units and ref range to cc type questions

---

packages/zambdas/src/patient/ai-interview/start/index.ts

Fix for https://github.com/masslight/ottehr/issues/2133

AI chat - Ask AI to not numerate questions

---

apps/intake/src/telemed/components/CallSideCard.tsx
apps/intake/src/telemed/components/SideCardList.tsx
apps/intake/src/telemed/components/index.ts
apps/intake/src/telemed/features/video-call/VideoControls.tsx
apps/intake/src/telemed/features/video-call/VideoRoom.tsx
apps/intake/src/telemed/pages/VideoChatPage.tsx

Issue 2082: Fix video call page mobile layout

---

apps/intake/src/pages/AIInterview.tsx
packages/zambdas/src/patient/ai-interview/start/index.ts

Fix for https://github.com/masslight/ottehr/issues/2095.

AI Chat - Improve completed chat experience

---

apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/CurrentMedications/CurrentMedicationsProviderColumn.tsx
apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/KnownAllergies/KnownAllergiesProviderColumn.tsx

Issue 1877: Add check for minimum number of characters for search

---

apps/ehr/src/components/patient/InsuranceContainer.tsx

Issue 2142. Prevent updating controlled checkbox with previous value after the form reset.

---

apps/ehr/src/features/css-module/pages/Procedures.tsx
apps/ehr/src/features/css-module/pages/ProceduresNew.tsx

Fix for https://github.com/masslight/ottehr/issues/2357.

Procedures - Disable creating new procedures and editing existing when progress note is signed

---

packages/zambdas/src/ehr/save-chart-data/index.ts
packages/zambdas/src/shared/chart-data/index.ts

Fix for https://github.com/masslight/ottehr/issues/2444.

Fix adding multiple diagnosis to chart simultaneously

---

packages/zambdas/src/ehr/save-chart-data/index.ts

Issue 2088. EHR. Progress Note. Diagnoses are saved incorrectly

---

apps/ehr/src/features/external-labs/components/OrderHistoryCard.tsx
apps/ehr/src/features/external-labs/components/labs-orders/LabsTableRow.tsx
apps/ehr/src/features/in-house-labs/components/InHouseLabsStatusChip.tsx
apps/ehr/src/features/in-house-labs/components/details/CollectSampleView.tsx
apps/ehr/src/features/in-house-labs/components/details/FinalResultCard.tsx
apps/ehr/src/features/in-house-labs/components/details/FinalResultView.tsx
apps/ehr/src/features/in-house-labs/components/details/InHouseLabOrderHistory.tsx
apps/ehr/src/features/in-house-labs/components/details/PerformTestView.tsx
apps/ehr/src/features/in-house-labs/components/orders/InHouseLabsTableRow.tsx
apps/ehr/src/features/in-house-labs/pages/InHouseLabOrderDetailsPage.tsx
packages/utils/lib/helpers/in-house-labs/index.ts
packages/utils/lib/types/data/in-house/in-house.helpers.ts
packages/utils/lib/types/data/in-house/in-house.types.ts
packages/utils/lib/types/data/in-house/index.ts
packages/utils/lib/utils/dateUtils.ts
packages/zambdas/src/ehr/create-in-house-lab-order/index.ts
packages/zambdas/src/ehr/get-in-house-orders/helpers.ts
packages/zambdas/src/ehr/get-in-house-orders/index.ts
packages/zambdas/src/ehr/get-lab-orders/helpers.ts
packages/zambdas/src/ehr/shared/inhouse-labs.ts

https://github.com/masslight/ottehr/issues/2393
https://github.com/masslight/ottehr/issues/2395

adds repeat tests to final view

---

packages/zambdas/src/ehr/submit-lab-order/index.ts
packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts
packages/zambdas/src/shared/pdf/types.ts

Order 2184

---

packages/zambdas/src/ehr/get-lab-orders/helpers.ts

Fix: fix corrected results map overwrite bug

---

apps/ehr/src/features/in-house-labs/components/WithInHouseLabsBreadcrums.tsx
apps/ehr/src/features/in-house-labs/components/details/CollectSampleView.tsx
apps/ehr/src/features/in-house-labs/components/details/InHouseLabOrderHistory.tsx
apps/ehr/src/features/in-house-labs/pages/InHouseLabOrderCreatePage.tsx
apps/ehr/src/features/in-house-labs/pages/InHouseLabOrderDetailsPage.tsx

https://github.com/masslight/ottehr/issues/2346

redesign "collect samples" page; add breadcrumbs; #2346

---

apps/ehr/src/components/PatientEncountersGrid.tsx
apps/ehr/src/pages/AppointmentPage.tsx

resolves https://github.com/masslight/ottehr/issues/2176

Patients page - Visit info navigation bug

---

apps/ehr/src/features/in-house-labs/components/WithInHouseLabsBreadcrums.tsx
apps/ehr/src/features/in-house-labs/components/details/FinalResultCard.tsx
apps/ehr/src/features/in-house-labs/components/details/FinalResultView.tsx
apps/ehr/src/features/in-house-labs/components/details/PerformTestView.tsx
apps/ehr/src/features/in-house-labs/components/details/ResultsEntryTable.tsx
apps/ehr/src/features/in-house-labs/components/details/ResultsEntryTableRow.tsx
apps/ehr/src/features/in-house-labs/pages/InHouseLabOrderCreatePage.tsx
apps/ehr/src/features/in-house-labs/pages/InHouseLabOrderDetailsPage.tsx

And adds some keys to mapped components
See "left to do" - https://github.com/masslight/ottehr/issues/2393#issuecomment-2931396968

Adds repeat button to final view 

---

apps/ehr/src/features/radiology/components/RadiologyTable.tsx
apps/ehr/src/features/radiology/components/RadiologyTableRow.tsx
apps/ehr/src/features/radiology/pages/RadiologyOrdersListPage.tsx

fix(radiology): add stat to radiology order table

---

apps/intake/src/pages/Homepage.tsx
apps/intake/tests/specs/telemed/homepage.spec.ts

Resolves https://github.com/masslight/ottehr/issues/2517

Homepage title updates

---

apps/ehr/src/features/css-module/pages/ProceduresNew.tsx

Fix for https://github.com/masslight/ottehr/issues/2494

Procedures: Move Procedure Document Statement to below “Performed”

---

apps/ehr/src/features/in-house-labs/components/details/CollectSampleView.tsx
apps/ehr/src/features/in-house-labs/components/details/ResultEntryRadioButton.tsx

https://github.com/masslight/ottehr/issues/2343

Handle neutral test styling in radio button

---

apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/MedicationCardField.tsx
apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/MedicationCardView.tsx
apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/utils.tsx
apps/ehr/src/features/css-module/hooks/useGetFieldOptions.ts
apps/ehr/tests/e2e/page/EditMedicationCard.ts

Issue 2455. Alphabetize In-house medications list

---

apps/ehr/src/components/patient/AddInsuranceModal.tsx
apps/ehr/tests/e2e/specs/patientRecordPage.spec.ts

Issue 2422. EHR. Patient information. Additional insurance information isn't saved when it was added with "Add insurance" feature

---

apps/ehr/src/features/css-module/pages/Allergies.tsx
apps/ehr/src/telemed/features/appointment/AppointmentSidePanel.tsx
apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/KnownAllergies/KnownAllergiesPatientColumn.tsx

Fix for https://github.com/masslight/ottehr/issues/836

EHR. Update "Allergies" in left sidebar according to answered/confirmed states.

---

apps/ehr/src/pages/SchedulePage.tsx
packages/utils/lib/utils/scheduleUtils.ts
packages/zambdas/src/ehr/schedules/get-schedule/index.ts

Resolves https://github.com/masslight/ottehr/issues/2321

Updates url for telemed locations

---

apps/ehr/src/pages/AddPatient.tsx

Resolves https://github.com/masslight/ottehr/issues/2405

Updates qrs copies in EHR

---

apps/ehr/src/pages/Appointments.tsx
apps/ehr/src/telemed/features/tracking-board/VisitTypeSelect.tsx
apps/ehr/src/telemed/state/tracking-board/tracking-board.store.ts

Fix of https://github.com/masslight/ottehr/issues/2680

EHR. Fix visit type multi-select dropdown clearing

---

apps/ehr/src/features/css-module/components/vitals/vision/VitalVisionEntry.ts
apps/ehr/src/features/css-module/components/vitals/vision/VitalsVisionCard.tsx
apps/ehr/src/features/css-module/components/vitals/vision/helpers.ts
packages/utils/lib/helpers/visit-note/map-vitals-to-display.helper.ts
packages/utils/lib/helpers/vitals/vitals-vision.helper.ts

Implementation of https://github.com/masslight/ottehr/issues/2440.

Change 'Vision' drop-down field to free text on Vitals screen

---

apps/ehr/src/features/css-module/components/hospitalization/HospitalizationForm.tsx

Issue 2408. Alphabetize 'Hospitalization' list

---

apps/ehr/src/components/patient/ResponsibleInformationContainer.tsx

Issue 2424. EHR. Patient information. Responsible party. All fields should be uneditable if "Self" option is selected.

---

apps/ehr/src/components/AppointmentTable.tsx
apps/ehr/src/components/AppointmentTableRow.tsx
apps/ehr/src/constants/index.ts
apps/ehr/src/features/css-module/components/SwitchIntakeModeButton.tsx

Resolves  https://github.com/masslight/ottehr/issues/2563 and https://github.com/masslight/ottehr/issues/2572

Minor Ehr Enhancements

---

apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/CurrentMedications/CurrentMedicationsProviderColumn.tsx

Fixing medication labels in medications search output so it has strength to avoid entries that look completely the same in dropdown

Fix medication names in search not having stength

---

apps/ehr/tests/e2e/specs/addPatientPage.spec.ts
apps/ehr/tests/e2e/specs/ehr.spec.ts
apps/ehr/tests/e2e/specs/patientRecordPageInsuranceSection.spec.ts

skip flaky ehr tests

---

packages/zambdas/src/shared/pdf/visit-details-pdf/visit-note-pdf-creation.ts

Issue 2235: Fix time spent with provider in visit note bug

---

apps/ehr/src/components/AppointmentTable.tsx

Resolves https://github.com/masslight/ottehr/issues/2563#issuecomment-2990146053

2563 regression

---

.vscode/cspell.json
apps/ehr/src/components/AppointmentTableRow.tsx
apps/ehr/src/features/css-module/components/progress-note/ProgressNoteDetails.tsx
apps/ehr/src/features/css-module/pages/ProceduresNew.tsx
apps/ehr/src/helpers/index.ts
apps/ehr/src/telemed/features/appointment/ReviewTab/components/LabResultsReviewContainer.tsx
apps/ehr/tests/e2e/specs/telemed/planTab.spec.ts
apps/intake/tests/global-setup/index.ts
packages/utils/lib/types/data/labs/labs.types.ts
packages/zambdas/src/ehr/shared/labs.ts
packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts
packages/zambdas/src/shared/pdf/types.ts

recheck spelling in apps

---

apps/ehr/tests/e2e-utils/seed-data/seed-ehr-appointment-data.json
packages/utils/lib/fhir/constants.ts
packages/zambdas/src/ehr/paperwork-to-pdf/index.ts
packages/zambdas/src/scripts/setup.ts
scripts/ottehr-setup.ts

Issue 1942 / fix. EHR. Docs. Privacy Policy and Paperwork folders do not allow to upload docs

---

packages/zambdas/src/shared/pdf/external-labs-order-form-pdf.ts
packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts
packages/zambdas/src/shared/pdf/types.ts

https://github.com/masslight/ottehr/issues/2507
External Orders Form: 
External Results Form: 
InHouse Results Form:

More result pdf updates

---

apps/ehr/src/features/external-labs/components/AOEDateQuestion.tsx
apps/ehr/src/features/external-labs/components/AOEFreeTextQuestion.tsx
apps/ehr/src/features/external-labs/components/AOEListQuestion.tsx
apps/ehr/src/features/external-labs/components/AOEMultiSelectListQuestion.tsx
apps/ehr/src/features/external-labs/components/AOENumberQuestion.tsx
apps/ehr/src/features/external-labs/components/AOEQuestion.tsx
apps/ehr/src/features/external-labs/components/AOEYesNoQuestion.tsx

resolve issue with default answers #2219

---

apps/ehr/src/telemed/features/appointment/AssessmentTab/components/DiagnosesContainer.tsx
packages/zambdas/src/ehr/save-chart-data/index.ts

Issue 2445. Empty dx field bug

---

packages/zambdas/src/ehr/get-lab-orders/helpers.ts

https://github.com/masslight/ottehr/issues/2909

Fix task search in get lab orders

---

packages/zambdas/src/scripts/load-in-house-labs-tests.ts

Fix: update load in house labs script for all envs

---

packages/utils/lib/fhir/constants.ts
packages/utils/lib/helpers/in-house-labs/index.ts
packages/utils/lib/types/data/labs/labs.constants.ts
packages/zambdas/src/cron/notifications-updater/index.ts
packages/zambdas/src/cron/send-message-cron/index.ts
packages/zambdas/src/ehr/change-telemed-appointment-status/helpers/helpers.ts
packages/zambdas/src/ehr/change-telemed-appointment-status/helpers/payments.ts
packages/zambdas/src/ehr/create-lab-order/index.ts
packages/zambdas/src/ehr/get-appointments/helpers.ts
packages/zambdas/src/ehr/get-lab-orders/helpers.ts
packages/zambdas/src/ehr/get-telemed-appointments/helpers/fhir-resources-filters.ts
packages/zambdas/src/ehr/get-telemed-appointments/helpers/fhir-utils.ts
packages/zambdas/src/ehr/get-telemed-appointments/index.ts
packages/zambdas/src/ehr/patient-account/update/index.ts
packages/zambdas/src/ehr/save-followup-encounter/helpers.ts
packages/zambdas/src/ehr/shared/harvest/index.ts
packages/zambdas/src/ehr/submit-lab-order/index.ts
packages/zambdas/src/ehr/update-lab-order-resources/index.ts
packages/zambdas/src/patient/bookable/list-bookables/index.ts
packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts
packages/zambdas/src/subscriptions/diagnostic-report/handle-lab-result/index.ts
packages/zambdas/src/subscriptions/questionnaire-response/sub-intake-harvest/index.ts

focused on shared files that could affect many zambdas
#2679

zambda package spell check pr 4 of n

---

apps/ehr/src/features/css-module/pages/Allergies.tsx
apps/ehr/src/features/css-module/pages/Hospitalization.tsx
apps/ehr/src/features/css-module/pages/MedicalConditions.tsx
apps/ehr/src/features/css-module/pages/ProceduresNew.tsx
apps/ehr/src/features/css-module/pages/SurgicalHistory.tsx
apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/MedicalHistoryDoubleCard.tsx

Resolves https://github.com/masslight/ottehr/issues/2407

Update copies in Ehr appointment - intake screens

---

apps/ehr/src/telemed/features/appointment/ReviewTab/ReviewAndSignButton.tsx

https://github.com/masslight/ottehr/issues/2659

Fix typo - sign not sing

---

apps/ehr/src/telemed/features/tracking-board/TrackingBoardTableRow.tsx

https://github.com/masslight/ottehr/issues/2744

Wrap reason for visit and reason for cancellation

---

apps/ehr/src/api/api.ts
apps/ehr/src/features/radiology/components/usePatientRadiologyOrders.ts
packages/zambdas/src/ehr/radiology/cancel-order/index.ts

https://github.com/masslight/ottehr/issues/2925

Delete radiology order bug

---

apps/ehr/src/features/external-labs/components/AOEFreeTextQuestion.tsx

max length for labs text is 150 characters #2467

---

apps/intake/src/pages/ThankYou.tsx

https://github.com/masslight/ottehr/issues/2641

update AI Bot copy

---

apps/ehr/src/telemed/features/appointment/AppointmentHeader.tsx

https://github.com/masslight/ottehr/issues/1466

Adds back button to virtual visit view

---

apps/ehr/src/telemed/features/tracking-board/TrackingBoardTableRow.tsx

https://github.com/masslight/ottehr/issues/2744

Overflow should be visible

---

packages/zambdas/src/ehr/create-update-medication-order/index.ts

Issue 2989. EHR. In-house Medications. "Delete" not working fix

---

.vscode/custom-dictionaries/medical-terms.txt
apps/ehr/src/features/css-module/components/medication-administration/mar/MarTableRow.tsx
apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/MedicationCardField.tsx
apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/MedicationCardView.tsx
apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/fieldsConfig.ts
apps/ehr/tests/e2e/specs/in-person/inHouseMedicationsPage.spec.ts
packages/utils/lib/fhir/medication-administration.ts
packages/utils/lib/types/api/medication-administration.types.ts
packages/zambdas/src/ehr/create-update-medication-order/index.ts
packages/zambdas/src/ehr/get-medication-orders/index.ts

https://github.com/masslight/ottehr/issues/2801
Original issue scope:
- Field label for Instructions should be 'Comments' on the detail page and 'Instructions' on other pages
Additional changes:
- Use actual field values when saving MedicationStatement; previously outdated values from the old MedicationAdministration were used
- Improved label texts, e.g., AssociatedDx -> Associated Dx; Give Date/Time -> Date/Time Given; expDate -> Expiration Date; and more
- Add possibility to override label values depending on form type

[Medications] fields update

---

packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts

https://github.com/masslight/ottehr/issues/3011
for full PDF, view here http://localhost:4002/in-person/fb86b791-6845-465e-a65b-e384fab78256/external-lab-orders/bb0e2e1c-f25e-48f4-8a2d-07a3e7895b97/order-details

Display observations without data in a nicer way

---

packages/zambdas/src/ehr/radiology/launch-viewer/index.ts

fix(radiology): add logging to launch viewer endpoint

---

packages/zambdas/src/ehr/submit-lab-order/helpers.ts
packages/zambdas/src/ehr/submit-lab-order/index.ts
packages/zambdas/src/shared/pdf/external-labs-order-form-pdf.ts
packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts
packages/zambdas/src/shared/pdf/pdf-utils.ts
packages/zambdas/src/shared/pdf/types.ts

Feat: update order form

---

apps/ehr/src/layout/PageContainer.tsx

https://github.com/masslight/ottehr/issues/3065

add copyright tooltip

---

packages/utils/lib/types/data/labs/labs.constants.ts
packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts

https://github.com/masslight/ottehr/issues/3011#issuecomment-3053103868
to view entire result pdf: http://localhost:4002/in-person/fb86b791-6845-465e-a65b-e384fab78256/external-lab-orders/bb0e2e1c-f25e-48f4-8a2d-07a3e7895b97/order-details

OBR NTE in result pdf

---

apps/ehr/src/features/css-module/components/progress-note/VisitDetailsContainer.tsx
apps/ehr/src/features/css-module/context/NavigationContext.tsx

https://github.com/masslight/ottehr/issues/1584

Add link from "progress notes" to "visit details"

---

packages/zambdas/src/ehr/submit-lab-order/index.ts

Came up during testing of manual submission of external labs: https://github.com/masslight/ottehr/issues/3049#issuecomment-3053256195

Throw error in submit lab if order is already submitted 

---

apps/ehr/src/components/dialogs/PaymentDialog.tsx
apps/ehr/src/features/css-module/parser/parser.ts
apps/ehr/src/telemed/features/appointment/AppointmentSidePanel.tsx
apps/ehr/src/telemed/features/appointment/PastVisits.tsx
apps/ehr/src/telemed/features/appointment/ReviewTab/components/PatientInformationContainer.tsx
apps/ehr/src/telemed/utils/getPatientName.tsx

Resolves https://github.com/masslight/ottehr/issues/2603

Ehr middle name format update

---

apps/ehr/src/components/WithTooltip.tsx
apps/ehr/src/features/css-module/pages/ProceduresNew.tsx
apps/ehr/src/layout/PageContainer.tsx
apps/ehr/src/telemed/features/appointment/AssessmentTab/components/BillingCodesContainer.tsx

updates from https://github.com/masslight/ottehr/issues/3065

update copy and add additional tooltips to UI

---

apps/ehr/src/features/external-labs/components/OrderCollection.tsx

https://github.com/masslight/ottehr/issues/3093

Submit lab bug

---

apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/EditableMedicationCard.tsx

Fix for https://github.com/masslight/ottehr/issues/3133.

DDI/DDA - Take drugId from Medication's code

---

apps/ehr/src/features/nursing-orders/components/details/OrderDetails.tsx

Issue 2894. EHR. Nursing Orders. Remove "Mark as Completed" button if status is completed

---

apps/ehr/src/features/css-module/hooks/useAppointment.ts
apps/ehr/src/features/css-module/routing/CSSRouting.tsx

Fix random errors like the ones shown in screenshots when tabs in the appointment table are clicked.

fix app crash

---

packages/zambdas/src/scripts/reflex-test-helper.ts

Quick fix for the reflex mock script. Came up in slack

Fix: update reflex mock script for all envs

---

packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts

to view entire result pdf: http://localhost:4002/in-person/fb86b791-6845-465e-a65b-e384fab78256/external-lab-orders/bb0e2e1c-f25e-48f4-8a2d-07a3e7895b97/order-details

Obr notes should come before obx observations

---

apps/ehr/src/features/external-labs/components/AOEQuestion.tsx
apps/ehr/src/features/external-labs/components/OrderCollection.tsx
apps/ehr/src/features/external-labs/components/details/DetailsWithResults.tsx
packages/zambdas/src/ehr/submit-lab-order/index.ts

https://github.com/masslight/ottehr/issues/3093 <- different approach to fixing this bug

refactor front end submit lab order call and fixes some little bugs

---

apps/ehr/src/pages/EditEmployee.tsx
packages/utils/lib/types/api/get-user.types.ts
packages/zambdas/src/ehr/get-user/index.ts

https://github.com/masslight/ottehr/issues/2466

Updates edit schedule button on employee page

---

apps/ehr/src/components/AppointmentTableRow.tsx

https://github.com/masslight/ottehr/issues/2637
https://github.com/masslight/ottehr/issues/3177

fix next label

---

apps/intake/src/pages/AIInterview.tsx

https://github.com/masslight/ottehr/issues/2490

Ai chat message bug

---

.vscode/settings.json
packages/zambdas/src/shared/candid.ts

making it a draft, since i don't know where to pull it into

RCM: re-reading appointment from FHIR after update (happening in sync)

---

apps/ehr/src/features/css-module/components/medication-administration/InteractionAlertsDialog.tsx
apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/EditableMedicationCard.tsx
apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/utils.tsx
packages/utils/lib/fhir/medication-administration.ts
packages/utils/lib/types/api/medication-administration.types.ts
packages/zambdas/src/ehr/create-update-medication-order/fhir-resources-creation.ts

Implementation of https://github.com/masslight/ottehr/issues/3162.

Show source of drug-drug interactions if available

---

apps/ehr/src/pages/Appointments.tsx
packages/utils/lib/types/api/get-appointments.types.ts
packages/zambdas/src/ehr/get-appointments/helpers.ts
packages/zambdas/src/ehr/get-appointments/index.ts

https://github.com/masslight/ottehr/issues/2821

remove active appointment dates before today

---

apps/ehr/src/components/dialogs/CancellationReasonDialog.tsx
apps/ehr/src/features/css-module/components/ChangeStatusDropdown.tsx
apps/ehr/src/helpers/activityLogsUtils.ts
apps/ehr/src/helpers/index.ts
apps/ehr/src/pages/AppointmentPage.tsx
packages/utils/lib/fhir/helpers.ts
packages/zambdas/src/ehr/change-in-person-visit-status/helpers/helpers.ts
packages/zambdas/src/ehr/sign-appointment/index.ts
packages/zambdas/src/patient/appointment/prebook-cancel-appointment/index.ts
packages/zambdas/src/patient/check-in/index.ts

https://github.com/masslight/ottehr/issues/2928

Status update activity logs

---

apps/ehr/src/features/external-labs/components/OrderCollection.tsx

https://github.com/masslight/ottehr/issues/3084
https://github.com/masslight/ottehr/issues/3105
https://github.com/user-attachments/assets/e07651cc-76a8-4de8-9e94-b21ebe6088f0

Better error handling within manual submit error dialog

---

packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts
packages/zambdas/src/shared/pdf/types.ts

https://github.com/masslight/ottehr/issues/3128
example of correctly sorted pdf http://localhost:4002/in-person/f75384d8-9836-47f7-8a79-250d7e8f0d12/in-house-lab-orders/5e698ab3-c3d7-4b1a-83c1-6c2399ba3737/order-details

Sort results in inhouse lab results pdf

---

apps/ehr/src/features/in-house-labs/pages/InHouseLabOrderCreatePage.tsx
packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts

https://github.com/masslight/ottehr/issues/3227

Make dx optional for inhouse lab

---

apps/ehr/src/telemed/features/appointment/ReviewTab/ReviewAndSignButton.tsx

https://github.com/masslight/ottehr/issues/3247

Remove pending lab results validation to sign progress note

---

apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/MedicationCardField.tsx

https://github.com/masslight/ottehr/issues/3239

Dont allow scroll within number field type

---

apps/ehr/src/telemed/features/appointment/PlanTab/components/GenerateExcuseDialog.tsx
apps/ehr/src/telemed/utils/school-work-excuse.helper.ts
packages/utils/lib/fhir/helpers.ts
packages/utils/lib/fhir/patient.ts
packages/zambdas/src/shared/pdf/pdf-utils.ts
packages/zambdas/src/shared/pdf/school-work-note-pdf.ts

Fix: fix excuse note spacing and include all qualifications

---

apps/ehr/src/features/in-house-labs/pages/InHouseLabOrderCreatePage.tsx

https://github.com/masslight/ottehr/issues/3233
https://github.com/user-attachments/assets/a3dcdd9f-0bf0-4b2b-9f5a-d2cc8d00e133

Default cpt code for inhouse labs

---

apps/ehr/src/features/css-module/routing/routesCSS.tsx

Fix for https://github.com/masslight/ottehr/issues/3302

Show "OystEHR AI" section in all modes

---

apps/ehr/src/features/nursing-orders/components/details/OrderDetails.tsx
apps/ehr/src/features/nursing-orders/components/orders/NursingOrdersTableRow.tsx
apps/ehr/src/telemed/features/appointment/PlanTab/PatientInstructionsCard.tsx
apps/ehr/src/telemed/features/appointment/ReviewTab/components/PatientInstructionsContainer.tsx

Fix for https://github.com/masslight/ottehr/issues/3212.

Fix rendering of multiline patient instructions

---

apps/ehr/src/features/external-labs/components/OrderCollection.tsx
packages/utils/lib/types/errors/index.ts
packages/zambdas/src/ehr/submit-lab-order/index.ts

https://github.com/masslight/ottehr/issues/3105#issuecomment-3089850929

External lab manual submit error handling

---

packages/zambdas/src/shared/candid.ts

adding mapping of relationships from parent to child ...  #3349

adding relationship mapping to be correct (#3349)

---

apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/MedicationCardView.tsx
apps/ehr/tests/e2e/page/EditMedicationCard.ts
apps/ehr/tests/e2e/specs/in-person/inHouseMedicationsPage.spec.ts

https://github.com/masslight/ottehr/issues/3356

[EHR] In-house orders; Order details; Remove redundant provider by

---

apps/ehr/src/components/patient/PatientFollowupForm.tsx

Fix for https://github.com/masslight/ottehr/issues/3362.
[screen-capture.webm](https://github.com/user-attachments/assets/7d62be43-5fd1-45ba-95c7-05fc12f6ef87)

Make Patient Followup "Message" to be multiline

---

apps/ehr/src/api/api.ts
apps/ehr/src/hooks/useGetPatientDocs.ts
apps/ehr/src/pages/AppointmentPage.tsx
packages/zambdas/src/ehr/paperwork-to-pdf/index.ts

Implementation for https://github.com/masslight/ottehr/issues/3368.

Add "Paperwork PDF" button to visit's details page

---

apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/utils.tsx
apps/ehr/src/features/css-module/components/medication-administration/statuses/MedicationStatusChip.tsx
apps/ehr/src/features/css-module/components/progress-note/InHouseMedicationsContainer.tsx
apps/ehr/src/features/css-module/components/progress-note/ProgressNoteDetails.tsx
packages/utils/lib/fhir/medication-administration.ts
packages/utils/lib/helpers/visit-note/progress-note-chart-data-requested-fields.helper.ts
packages/zambdas/src/ehr/get-medication-orders/index.ts
packages/zambdas/src/ehr/sign-appointment/index.ts
packages/zambdas/src/shared/pdf/types.ts
packages/zambdas/src/shared/pdf/visit-details-pdf/visit-note-pdf-creation.ts
packages/zambdas/src/shared/pdf/visit-note-pdf.ts

Issue 3161: Add in-house medications to progress note

---

apps/ehr/src/pages/AppointmentPage.tsx
packages/utils/lib/helpers/paperwork/paperwork.ts
packages/zambdas/src/ehr/paperwork-to-pdf/index.ts

Make sure the "paperwork" is selected from existing documents.

Fix paperwork to pdf

---

packages/zambdas/src/shared/pdf/visit-note-pdf.ts

fix release-dev merge lint

---

packages/zambdas/src/ehr/paperwork-to-pdf/index.ts

Fix for https://github.com/masslight/ottehr/issues/3412.

Fix "Paperwork PDF" downloading.

---

packages/zambdas/src/shared/pdf/visit-note-pdf.ts

https://github.com/masslight/ottehr/issues/3024
I tried to use [handleBadSpaces](https://github.com/masslight/ottehr/blob/handle-pdf-spacing/packages/zambdas/src/shared/pdf/pdf-utils.ts#L43) but that didn't work as well.

fix: handle spacing issue in visit note pdf

---

packages/zambdas/src/shared/pdf/external-labs-order-form-pdf.ts
packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts

Seeing very infrequent errors in pdf generation but unable to pinpoint without logs

logging: add pdf logs

---

apps/ehr/src/features/css-module/components/medication-administration/mar/MarTable.tsx
apps/ehr/src/features/css-module/components/medication-administration/mar/MedicationInteractionsAlertButton.tsx

Fix for https://github.com/masslight/ottehr/issues/3437 and https://github.com/masslight/ottehr/issues/3438

In-house medications page bugfixes related to DDI/DAI

---

apps/ehr/src/features/css-module/components/progress-note/ProgressNoteDetails.tsx
apps/ehr/src/telemed/features/appointment/ExamTab/components/ExamCommentField.tsx
apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/ChiefComplaint/ChiefComplaintProviderColumn.tsx
apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/SurgicalHistory/ProceduresNoteField.tsx
apps/ehr/src/telemed/features/appointment/MedicalHistoryTab/SurgicalHistory/SurgicalHistoryProviderColumn.tsx
apps/ehr/src/telemed/features/appointment/ReviewTab/ReviewTab.tsx
apps/ehr/src/telemed/hooks/useDebounceNotesField.ts
packages/utils/lib/helpers/visit-note/progress-note-chart-data-requested-fields.helper.ts
packages/zambdas/src/ehr/get-chart-data/index.ts
packages/zambdas/src/shared/pdf/visit-details-pdf/visit-note-pdf-creation.ts

Issue 3293: Fix notes and comment fields text issues

---

apps/ehr/src/features/css-module/components/medication-administration/mar/MarTableRow.tsx
packages/zambdas/src/shared/chart-data/index.ts

https://github.com/masslight/ottehr/issues/3107
https://github.com/masslight/ottehr/issues/3109

In house medications and MAR table medication dosages

---

apps/ehr/src/features/nursing-orders/components/orders/NursingOrdersTableRow.tsx

implement nursing order delete modal

---

apps/ehr/src/components/OrdersIconsToolTip.tsx

https://github.com/masslight/ottehr/issues/3425#issuecomment-3166842779

fix nursing hover shows 0 orders

---

scripts/deploy/aws/bin/deploy.ts
scripts/deploy/aws/bin/update-config.ts
scripts/deploy/aws/lib/ottehr-infra-stack.ts

Revert "feat(deploy): add project name for aws deploys"

---

scripts/deploy/aws/bin/deploy.ts
scripts/deploy/aws/lib/ottehr-data-stack.ts

[AWS CDK Docs](https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_s3_deployment.BucketDeployment.html#distribution)

fix(deploy): Invalidate distribution on website upload

---

apps/intake/src/pages/PaperworkPage.tsx

https://github.com/masslight/ottehr/issues/3402

feat: remove warning of 'self-pay'

---

packages/zambdas/src/subscriptions/communication/communication-subscription/index.ts

---
also considers leaving the secret field empty

fix report issue email bug won't send if bcc exists in 'to' email field

---

packages/zambdas/src/shared/pdf/pdf-utils.ts

https://github.com/masslight/ottehr/issues/3700
example of correctly generate results pdf: http://localhost:4002/in-person/abb4ebf6-f447-45b0-a4a2-30dc7a734e30/external-lab-orders/93d79742-3b74-451b-b2ed-aa1384934c5a/order-details

Multi page pdf attachment bug

---

packages/utils/lib/helpers/check-office-open.ts
packages/zambdas/test/schedules-and-slots/walkin-availability.test.ts

resolves https://github.com/masslight/ottehr/issues/3508

take office open into account

---

apps/ehr/src/telemed/features/appointment/ReviewTab/AddendumCard.tsx
apps/ehr/src/themes/ottehr/colors.ts

https://github.com/masslight/ottehr/issues/3696

feat: add Addendum name/date reminder note

---

apps/ehr/src/features/css-module/components/medication-administration/medication-editable-card/MedicationCardField.tsx
apps/ehr/src/features/css-module/hooks/useGetFieldOptions.ts
apps/ehr/tests/e2e/page/EditMedicationCard.ts
apps/ehr/tests/e2e/specs/in-person/inHouseMedicationsPage.spec.ts

Issue 3244: Fix medications list search

---

packages/utils/lib/types/data/examination/in-person.config.ts

Issue 3166: Change in-person exams config

---

packages/utils/lib/types/data/labs/labs.constants.ts
packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts
packages/zambdas/src/shared/pdf/types.ts

https://github.com/masslight/ottehr/issues/3655

get performing site info from obx

---

apps/ehr/src/features/css-module/components/screening/AskThePatient.tsx
apps/ehr/src/features/css-module/components/screening/useScreeningQuestionsHandler.ts
packages/utils/.ottehr_config/index.ts
packages/utils/.ottehr_config/screening-questions/index.ts
packages/utils/lib/configuration/index.ts
packages/utils/lib/configuration/questionnaire/index.ts
packages/utils/lib/types/api/chart-data/chart-data.constants.ts
packages/utils/lib/types/api/chart-data/chart-data.types.ts
packages/utils/lib/types/data/index.ts
packages/utils/lib/types/data/screening-questions/config.ts
packages/utils/lib/types/data/screening-questions/constants.ts
packages/utils/lib/types/data/screening-questions/index.ts
packages/utils/lib/types/data/screening-questions/types.ts
packages/utils/lib/types/data/screening-questions/utils.ts
packages/utils/tsconfig.json
packages/zambdas/src/shared/chart-data/index.ts

Refactor screening questions component to be configurable and add new DateRange field type to enable required customer configurations.

[EHR]: add screening questions config

---

apps/ehr/src/telemed/features/appointment/ExamTab/components/ExamForm.tsx
apps/ehr/src/telemed/hooks/useResetAppointmentStore.ts

Issue 3740: Fix exam notes and comments

---

packages/utils/lib/types/data/labs/labs.constants.ts
packages/zambdas/src/ehr/get-lab-orders/helpers.ts

https://github.com/masslight/ottehr/issues/3615#issuecomment-3245494948

Include reflex tag in query

---

packages/zambdas/src/ehr/get-unsolicited-results-resources/helpers.ts
packages/zambdas/src/ehr/shared/labs.ts
packages/zambdas/src/ehr/update-lab-order-resources/helpers.ts
packages/zambdas/src/scripts/reflex-test-helper.ts
packages/zambdas/src/subscriptions/diagnostic-report/handle-lab-result/index.ts

https://github.com/masslight/ottehr/issues/3802

Unsolicited result bugs

---

packages/utils/lib/fhir/insurance.ts
packages/zambdas/src/ehr/shared/harvest/index.ts

EHR. Patient record. Insurance data isn't shown.

---

apps/ehr/src/components/AppointmentTableRow.tsx
packages/utils/lib/helpers/helpers.ts

Issue 3540 / fix. Switch qualification 'OD' with 'DO' for physician

---

apps/ehr/src/components/ProfilePhotoImagePicker.tsx

https://github.com/masslight/ottehr/issues/3816

[EHR]: Patient. Photo isn't updated without reloading

---

apps/ehr/src/features/immunization/components/OrderDetailsSection.tsx

Fix for https://github.com/masslight/ottehr/issues/3846

Immunization. Fix dose validation

---

packages/zambdas/src/shared/candid.ts

send location description to candid as service facility name.

---

packages/zambdas/src/shared/pdf/discharge-summary-pdf.ts

Issue 3824. Discharge Papers. Treating physician should be assigned provider

---

apps/ehr/src/components/patient/AddInsuranceModal.tsx
apps/ehr/src/components/patient/InsuranceContainer.tsx
packages/utils/lib/deployed-resources/questionnaires/ehr-insurance-update-questionnaire.json
packages/zambdas/src/ehr/shared/harvest/index.ts

https://linear.app/zapehr/issue/OTR-732/ehr-insurance-type-field-change-from-required-to-optional
wrong pr: https://github.com/masslight/ottehr/pull/3949

EHR. Making insurance-type field in visit view optional

---

packages/utils/lib/deployed-resources/questionnaires/ehr-insurance-update-questionnaire.json

Skipping 1.0.2 one i forgot to add with previous changes, related to [this](https://linear.app/zapehr/issue/OTR-732/ehr-insurance-type-field-change-from-required-to-optional) issue

Bump insurance questionnaire version

---

packages/zambdas/src/ehr/update-lab-order-resources/helpers.ts

https://github.com/masslight/ottehr/pull/3803#discussion_r2316952570

Adds ifMatch to dr put request

---

packages/zambdas/src/ehr/create-lab-order/index.ts
packages/zambdas/src/ehr/submit-lab-order/helpers.ts
packages/zambdas/src/ehr/submit-lab-order/index.ts
packages/zambdas/src/ehr/update-lab-order-resources/index.ts
packages/zambdas/src/shared/pdf/external-labs-label-pdf.ts
packages/zambdas/src/shared/pdf/external-labs-order-form-pdf.ts
packages/zambdas/src/shared/pdf/labs-results-form-pdf.ts

https://linear.app/zapehr/issue/OTR-750/capitalize-order-numbers#comment-235bb244

use requisition or req number in stead of order number for external labs

---

apps/ehr/src/features/css-module/components/progress-note/ProgressNoteDetails.tsx

Issue 4045: Fix notes for sections in progress note

---

apps/intake/src/features/paperwork/useAutofill.tsx

resolves https://github.com/masslight/ottehr/issues/2656

revert fancy saved value restoration for auto-fill

---

packages/zambdas/package.json
packages/zambdas/src/scripts/get-coverage-eligibility-responses.ts

just a zambda helper script to search for the most recent eligibility responses, and attempt to detect insurance type, like Medicaid

add a script to search for eligibility responses

---

apps/ehr/src/features/external-labs/components/AOEDateQuestion.tsx
apps/ehr/src/features/external-labs/components/AOEListQuestion.tsx
apps/ehr/src/features/external-labs/components/AOEMultiSelectListQuestion.tsx
apps/ehr/src/features/external-labs/components/OrderCollection.tsx

https://linear.app/zapehr/issue/OTR-671/ehr-labs-aoe-value-selection

Save answer option id rather than valueString and fix date bug

---

packages/zambdas/package.json
packages/zambdas/src/shared/communication.ts

small changes to email scripts, sender on lowers

Template cp

---

packages/zambdas/src/ehr/submit-lab-order/index.ts

https://linear.app/zapehr/issue/OTR-823/ehr-external-labs-psc-tests-stay-in-sent-status-results-not-received

Fix psc submit bug

---

apps/ehr/src/telemed/features/appointment/ApplyTemplate.tsx

Issue 4038: Disable global templates select for locked appointments

---

apps/ehr/src/components/AppointmentTabs.tsx
apps/ehr/src/features/css-module/components/progress-note/ProgressNoteDetails.tsx

Issue 4181. After Supervisor clicks Confirm Take them back to Discharged tab

---

apps/intake/src/features/paperwork/PagedQuestionnaire.tsx
apps/intake/src/pages/PaperworkPage.tsx

Issue 2656. Patient. "Error validating form" caused by Responsible party address.

---

apps/ehr/src/components/AppointmentTableRowMobile.tsx
apps/ehr/src/features/css-module/components/progress-note/RecordAudioContainer.tsx

Mobile encounter recordings

---

package-lock.json

fix npm critical warnings

---

packages/zambdas/src/shared/communication.ts

this disables ottehr from bcc'ing ourselves on every appointment email. this should not disable bcc's on report issue emails

disable bcc ottehr

---

apps/ehr/src/components/ReportsMenu.tsx
apps/ehr/src/pages/Data.tsx

start data page reports issue #3869

---

packages/zambdas/bundle.ts
packages/zambdas/src/shared/icd-10-search.ts

https://linear.app/zapehr/issue/OTR-927/in-person-radiology-create-new-order-fails

Fix path to ICD-10-CM file

---

apps/ehr/src/features/css-module/routing/routesCSS.tsx

This route was changed in another place but forgot to update here as well

Fix labs reflex / pdf report route bug

---

apps/ehr/tests/e2e-utils/seed-data/seed-ehr-appointment-data.json
packages/utils/lib/types/data/examination/in-person.config.ts

Revert "Remove 'LLL' option from Abdomen Tender dropdown across examination system"
